### ISSUE TITLE
Can't install the HASS.Agent-Notifier integration

### ISSUE THREAD

**Issue by FiftyFour7250** [LAB02-Research/HASS.Agent#1]
Hey. I have problems installing the integration, I wrote about it [here ](https://github.com/LAB02-Research/HASS.Agent-Notifier/issues/1)but just in case you don't follow the issues in that repository, I hurried to write here)

**Comment by LAB02-Admin** [comment]
Hi @FiftyFour7250, you're right, I'm still waiting for @ludeeus to [accept my pull-request](https://github.com/hacs/default/pull/1137)! As soon as that's done, it'll show up in HACS.

Until then, you can manually install by [downloading the .zip from here](https://github.com/LAB02-Research/HASS.Agent-Notifier/archive/refs/heads/master.zip), then extract the content of `HASS.Agent-Notifier-master\custom_components` into the `custom_components` folder of your Home Assistant instance.

Make sure it looks like this:

![image](https://user-images.githubusercontent.com/81011038/144011315-3f7de83f-ed16-4ee5-bf59-7529688ebade.png)

Or you could just wait untill it's reviewed, I'll post a message here when that's done.

**Comment by LAB02-Admin** [comment]
Closing, [continuing here](https://github.com/LAB02-Research/HASS.Agent-Notifier/issues/1).
