### ISSUE TITLE
Default hotkey for quick actions blocks the @ character on German keyboards

### ISSUE THREAD

**Issue by xpac1985** [LAB02-Research/HASS.Agent#10]
Hey,
the default hotkey for quick actions (CTRL + ALT + Q) blocks the @ character on German keyboards.
Took me a little to figure out whick of my new toys didn't want me to send mails anymore ;-)
May I recommend to pick a different default hotkey, or not to enable it by default, or...

Thanks for your work!

**Comment by LAB02-Admin** [comment]
Ah, nasty, thanks for letting me know. I'll disable it by default, add a warning for German users when enabling it while still having the default hotkey configured and a general headsup for other languages.

**Comment by LAB02-Admin** [comment]
Added in v2022.1.4
