### ISSUE TITLE
Feature: DirectX 12 Support

### ISSUE THREAD

**Issue by minooch** [LAB02-Research/HASS.Agent#101]
Hi,

Would it be possible to make ActiveWindowSensor support DirectX 12? Currently it shows a status of busy when running a DirectX 12 game.

Cheers

**Comment by LAB02-Admin** [comment]
Interesting, no idea. I'll do some tests and let you know :)

**Comment by LAB02-Admin** [comment]
I've created a ticket: [hassagent-134](https://lab02research.youtrack.cloud/issue/hassagent-134)

Closing this one to keep the github list tidy, but I'll report back here once it's implemented!
