### ISSUE TITLE
Feature: Choose where Webview appears

### ISSUE THREAD

**Issue by Majumafoo** [LAB02-Research/HASS.Agent#102]
**Request Details**
I would like to choose where on my desktop the WebView opens.
As things are, it opens bottom right corner of my primary display. I hope to select the bottom right corner of my secondary display, or wherever else someone could want it.

**Proposed Solution**
An option in the menu to allow a user to select a display and corner/location seems like a reasonable UI design.

**Other Considerations**
I acknowledge that this could be a limitation of the Windows UI. If so, I'd be keen to hear of any workarounds that may exist.

**Comment by LAB02-Admin** [comment]
Hi @Majumafoo,

There's already a request to have it remember its location (so you can drag it around): [hassagent-97](https://lab02research.youtrack.cloud/issue/hassagent-97). But the UI idea is a nice touch, I've added it to the ticket!

For a quick workaround, you can make WebView command. These already support setting it startup location (by dragging the screen). Then go to Quick Actions, and add your new webview command, binding it to a hotkey. That way you can bring it up on the position that you want, using the configured hotkey.

**Comment by LAB02-Admin** [comment]
I'm closing this ticket, not because I'm not doing it, but to keep the GitHub list tidy and all my todo's in one place. I'll report back here when I've fixed this!

**Comment by Majumafoo** [comment]
Thanks for the reply and insight!

The quick command suggestion works, so that's nice -thank you
Excited for the default starting position.

Thanks again :)
