### ISSUE TITLE
Bug: WebView Preview does not update preview size when "keep page loaded" option is selected

### ISSUE THREAD

**Issue by Majumafoo** [LAB02-Research/HASS.Agent#103]
**The Bug**
WebView Preview does not load when "keep page loaded in background" option is selected.

**To Reproduce**
*Intended Behaviour*
1. Open Configuration -> Tray Icon
2. Input relevant URL
3. Select 'show webview'
4. **Deselect** 'keep page loaded in the background'
5. Change size of WebView
6. Press 'show preview'
7. Observe change in preview.
---
*Unintended Behaviour* -see screenshot of config
1. Open Configuration -> Tray Icon
2. Input relevant URL
3. Select 'show webview'
4. **Select** 'keep page loaded in the background'
5. Change size of WebView
6. Press 'show preview'
7. Observe no change.
![config](https://user-images.githubusercontent.com/45857221/176364021-067f5932-e7aa-4b96-ac3c-99c9e2e127b4.png)

---
**Expected Behavior**
I expect the preview to change size in the same way regardless of if "keep page loaded..." is selected

---
**Machine Info**
![winver](https://user-images.githubusercontent.com/45857221/176364025-b7a8a705-0a8a-40f1-b413-046a4adb9fed.png)

---
**More Info:**
 - [x] Installed via installer
 - [ ] Installed manually
 - [x] Problem occurs in HASS.Agent
 - [ ] Problem occurs in Satellite Service

**Comment by LAB02-Admin** [comment]
Hey @Majumafoo,

I think this is a problem with the preview button. Can you please confirm this by resizing the webview, then restarting HASS.Agent and see if it correctly remembered the position? After the restart, the preview button should work as well for the new position.

**Comment by LAB02-Admin** [comment]
> which I believe is unintentional.

And you are right :) Will fix, thanks for confirming

**Comment by LAB02-Admin** [comment]
Fixed in the latest beta: https://github.com/LAB02-Research/HASS.Agent/releases/tag/2022.13.0-beta2
