### ISSUE TITLE
Feature: Support NATS.io-based MQTT server without QoS=2 support

### ISSUE THREAD

**Issue by robinsmidsrod** [LAB02-Research/HASS.Agent#105]
**Is your feature request related to a problem? Please describe.**
I'm using NATS.io for MQTT server, and it doesn't support QoS=2, which causes disconnections all the time.

**Describe the solution you'd like**
Avoid using QoS=2, or allow the QoS max level to be set.

**Comment by LAB02-Admin** [comment]
Good point @robinsmidsrod, will do! 

Created a ticket for this request: [hassagent-118](https://lab02research.youtrack.cloud/issue/hassagent-118).
I'm closing this GitHub ticket, not because I'm not doing it, but to keep everything centralised. I'll post back here when it's implemented :)
