### ISSUE TITLE
Feature: Connect to the host HA when not in local network (using a notebook outside your local network)

### ISSUE THREAD

**Issue by ASchneiderBR** [LAB02-Research/HASS.Agent#106]
Hello! Thanks for creating this great app, this is just amazing work!

I was wondering if it would be possible to type both a local IP and remote IP address and have Hass Agent know when it is not connected to the local network and use the secondary IP to connect to the host HA?

This would be great when I use notebook outside my local network and could still connect to the HA instance outside my home, over the internet. Since I've already set up my DDNS and opened the correct ports, this would be a great feature to have.

Thanks again, have a great day!

**Comment by LAB02-Admin** [comment]
That's a good idea, why not :)

Created a ticket for this request: [hassagent-119](https://lab02research.youtrack.cloud/issue/hassagent-119).
I'm closing this GitHub ticket, not because I'm not doing it, but to keep everything centralised. I'll post back here when it's implemented :)
