### ISSUE TITLE
Is it possible to support MQTT discovery?

### ISSUE THREAD

**Issue by ivanlee1007** [LAB02-Research/HASS.Agent#11]
It would be great if all local sensors can be discovered by home assistant as entities.
https://www.home-assistant.io/docs/mqtt/discovery/
And thanks for your wonderful work!

**Comment by LAB02-Admin** [comment]
Hi @ivanlee1007,

They should already be discovered by HA as entities. Are they not showing up in your instance at all, or do you mean something else?

**Comment by ivanlee1007** [comment]
Sorry they are just not showing in my instance at all so I thought it may not support MQTT discovery.
I will keep trying and hope I can find where the problem is in my HA.
Thanks.

**Comment by LAB02-Admin** [comment]
Maybe I can still help. For starters, could you look through HASS.Agent's logs to see if there are any exceptions? If you've used the installer, they're located in `%appdata%\LAB02 Research\HASS.Agent\Logs`.

I'm assuming you configured MQTT by the way, and its status shows as 'ok' in the main window.

If there are no exceptions or errors showing in the logs, could you checking Home Assistant's logs? You can find them by going to Configuration -> Settings -> Logs.

You can also try going to Configuration -> Devices & Services -> Devices, then type the name of your PC. Click on your device, and there should be a list of entities under 'Sensors'.

**Comment by ivanlee1007** [comment]
Hi @LAB02-Admin,

After some tests, I found the problem should be a customized mqtt setting in my HA's configuration.yaml file:

mqtt:
  discovery: true
  discovery_prefix: ha    <-- This customized discovery_prefix should be the problem.

When I change it back to default string: 'homeassistant', everything just works fine. But if I change it to 'ha' (I use it for my other devices), nothing will show up in my device list.

So my question is:  Is it possible to set a customized discovery_prefix in HASS.Agent?  
It would be great if I can change it so I don't need to modify config in all of my devices. 
But, anyway, really thanks for your kindly support.

**Comment by LAB02-Admin** [comment]
Sure, no problem. Will add it to the next version.

**Comment by LAB02-Admin** [comment]
Added!

**Comment by ivanlee1007** [comment]
Thanks a lot! It works great!
