### ISSUE TITLE
New Features

### ISSUE THREAD

**Issue by milandzuris** [LAB02-Research/HASS.Agent#111]
Minimize all windows, Turn off Screen - Black Screen, Maximize all windows, Login to PC with hass agent after lock pc.

**Comment by LAB02-Admin** [comment]
> Minimize all windows

You can use this script for a Powershell command: 

```ps
(New-Object -ComObject Shell.Application).MinimizeAll()
``` 

> Turn off Screen - Black Screen

You can use this script for a Powershell command:

```ps
(Add-Type '[DllImport(\"user32.dll\")]public static extern int SendMessage(int hWnd,int hMsg,int wParam,int lParam);' -Name a -Pas)::SendMessage(-1,0x0112,0xF170,2)
```

> Maximize all windows

You can use this script for a Powershell command:

```ps
(Get-Process | Where {$_.MainWindowTitle}).MainWindowTitle | % {
    $wshell = (New-Object -ComObject wscript.shell)
    $wshell.AppActivate($_)
    sleep 1
    $wshell.SendKeys("% x")
    sleep 1
}
```

> Login to PC with hass agent after lock pc

That's not possible, Windows prohibits applications from messing with the login screen.
