### ISSUE TITLE
Agent Closes

### ISSUE THREAD

**Issue by Lucho99se** [LAB02-Research/HASS.Agent#116]
The windows agent closes automatically, once it connects all the services

**Comment by LAB02-Admin** [comment]
I can't help you with this little information. At least provide some logs, ideally with extended logging enabled.

Create a new ticket using the Bug report template:

![image](https://user-images.githubusercontent.com/81011038/178022619-dd6c007d-a04e-4d73-85b4-72052cca5f0f.png)
