### ISSUE TITLE
Satellite Commands default to switch

### ISSUE THREAD

**Issue by JvdMaat** [LAB02-Research/HASS.Agent#117]
When creating a button in the Satellite Commands, the GUI says it's a button (ie, a Sleep Command). But when clicking save, it shows up as a Switch in MQTT.
Closing the Command window and re-opening then clicking Modify on the Command shows it as a switch.
Repeatedly fixing it does not solve the problem.

The regular user HASS.Agent Commands work fine as buttons.

**Comment by LAB02-Admin** [comment]
Hey @JvdMaat,

That's even the case with the [latest beta](https://github.com/LAB02-Research/HASS.Agent/releases/tag/2022.13.0-beta1)?
