### ISSUE TITLE
Availability doesn't change on shutdown

### ISSUE THREAD

**Issue by miit86** [LAB02-Research/HASS.Agent#12]
Hi,

Love your work, Sensor updates are OK now.
I use the Agent on my PC that is connected with my wifi.

When I use the shutdown command the PC shuts down. :P 
but the "homeassistant/sensor/<PC-NAME>/availability" doesn't change from online to offline.
It would be nice if I can use the availability as status for On or Off.

I know there are other ways to accomplish this. but I realy love the usage of MQTT

**Comment by LAB02-Admin** [comment]
Good call, I need to catch Windows' shutdown announcement. Not that difficult, will add in the next version.

Thanks!

**Comment by LAB02-Admin** [comment]
Fixed!
