### ISSUE TITLE
Feature: Actionable notifications

### ISSUE THREAD

**Issue by TeDeVPrime** [LAB02-Research/HASS.Agent#121]
I don't see it here but can we please! have actions in the notifications?

i have set my doorbell camera to send me a notification when someone rings. i want to be able to open the door from the notification with a button or two.

yes i can do this now with a macro but this is not a nice solution.

just found out the list of the features. i saw this request in there. hope we see it soon.
thanks for the good work

**Comment by LAB02-Admin** [comment]
Added to latest release
