### ISSUE TITLE
Bug: Session State showing Unlocked on logon screen after boot

### ISSUE THREAD

**Issue by ITensEI** [LAB02-Research/HASS.Agent#126]
**Describe the bug**
Session State shows Unlocked on boot before user login. 

**To Reproduce**
1. Go to your PC
2. Click on the power button
3. Wait for login screen
4. Check HA to see Session State = Unlocked
5. Automations fail

**Expected behavior**
Session State is a local sensor. Expected to start on logon when the HASS.Agent process starts not satellite. Should be Unavailable until then

**Screenshots**
![image](https://user-images.githubusercontent.com/9561099/179795288-4e46e31d-1ec0-41d8-9471-72a9d27ff3a3.png)

**Misc info (please complete the following information):**
 - Windows build (ideally screenshot/info of `winver.exe` output): 
![image](https://user-images.githubusercontent.com/9561099/179795437-4562e0d0-8c30-4188-a10e-849f69673229.png)

 - Windows' UI language:  English
 - HASS.Agent version:  2022.12.0

Please check what's applicable (multiple answers possible):

 - [x] Installed via installer
 - [ ] Installed manually
 - [x] Problem occurs in HASS.Agent
 - [ ] Problem occurs in Satellite Service

**Additional context**

**Logs**
If possible, please provide the logs of HASS.Agent and - if applicable - the Satellite Service. You can find HASS.Agent's logs by going to the main window, then `Configuration` -> `Logging` -> `open logs folder`. The Satellite Service's logs are in the same window, but the `Satellite Service` tab -> `open service logs folder`. If you want, you can mail them to lab02research@outlook.com

**Comment by LAB02-Admin** [comment]
Do you have FastBoot enabled in Windows?

**Comment by ITensEI** [comment]
Yes I do. I've managed to use LastSystemStateChange for a workaround for now. With HASS workstation service I used before it wouldn't load any sensors before the unlock as it didn't run as a service

**Comment by LAB02-Admin** [comment]
Ok, FastBoot is basically hibernate so that causes unexpected behavior after a reboot. I find that it doesn't really boot noticably faster (ironically), and disable it to prevent stuff like this. But ymmv.

Thanks for the info :)
