### ISSUE TITLE
Bug: State max length is 255 characters.

### ISSUE THREAD

**Issue by ITensEI** [LAB02-Research/HASS.Agent#127]
**Describe the bug**
Audio Sessions sensor is blank and throwing errors due to reaching state character limit. 
Shows the JSON as the state if it's within char limit otherwise will show [] as the state.

**To Reproduce**
Check the Audio Session sensor. 
Check Logs and will see the error

**Expected behavior**
State should represent if there's an active audio session and the rest should be passed as attributes.
Hopefully should be fixed in next release when [hassagent-72](https://lab02research.youtrack.cloud/issue/hassagent-72) is implemented

**Misc info (please complete the following information):**
Windows build (ideally screenshot/info of winver.exe output):
![image](https://user-images.githubusercontent.com/9561099/179828119-c62a84a5-2c0e-4a63-a724-cd4987c953c3.png)

Windows' UI language: English

HASS.Agent version: 2022.12.0

Please check what's applicable (multiple answers possible):

 - [x] Installed via installer
 - [ ] Installed manually
 - [x] Problem occurs in HASS.Agent
 - [ ] Problem occurs in Satellite Service

**Logs**
`Exception in message_received when handling msg on 'homeassistant/sensor/TENSE_PC/TENSE_PC_audio/TENSE_PC_audio_audio_sessions/state': '[ { "Application": "Spotify", "Muted": false, "MasterVolume": 100.0, "PeakVolume": 9.9636396E-05 }, { "Application": "@%SystemRoot%\\System32\\AudioSr..", "Muted": false, "MasterVolume": 100.0, "PeakVolume": 5.1592536 } ]' Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 47, in wrapper msg_callback(msg) File "/usr/src/homeassistant/homeassistant/components/mqtt/sensor.py", line 302, in message_received self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 532, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 646, in _async_write_ha_state self.hass.states.async_set( File "/usr/src/homeassistant/homeassistant/core.py", line 1438, in async_set state = State( File "/usr/src/homeassistant/homeassistant/core.py", line 1099, in __init__ raise InvalidStateError( homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.tense_pc_audio_sessions. State max length is 255 characters.`

**Comment by LAB02-Admin** [comment]
Hey @ITensEI,

That's a known limitation, I'm working on attributes integration:

https://lab02research.youtrack.cloud/issue/hassagent-72
