### ISSUE TITLE
Bug: MQTT messages are not sent with retain flag although HASS.agent is set to do so

### ISSUE THREAD

**Issue by TarcisioMenezes** [LAB02-Research/HASS.Agent#128]
**Describe the bug**
Although I have marked the option "retain flag" for MQTT, it seems it doesn't work. Checked with some MQTT clients and I don't see the sensor messages being sent as retained. 
I can confirm that If I restart my Home Assistant server, all the sensors from Hass.agent will change to "Unknown" until the MQTT broker gets another updated message. (Occurs for both Hass.agent and Satellite Service sensors)

**Expected behavior**
I was expecting the #/state topic messages to be sent with a retain flag then Home Assistant would show the last sensors states after restart.
 
For instance, if I inspect the topic "homeassistant/sensor/WINDOWS_10/WINDOWS_10_lastboot/state" there is not retain flag, therefore the state of the entity inside Home Assistant will be "unknown" until I either restart Hass.agent, Windows or the entity changes its state (which can take days for some entities. E.g. Last boot entity).

**Screenshots**
![image](https://user-images.githubusercontent.com/12872368/180702114-39b9ff7f-038d-4f25-8905-26973d4842bf.png)

![image](https://user-images.githubusercontent.com/12872368/180702839-d54f2fac-187e-4f45-8f8f-7aff9c6d8323.png)

![image](https://user-images.githubusercontent.com/12872368/180701623-974a9ec0-f915-4a29-b140-7afac7aceb2a.png)

**Misc info (please complete the following information):**
 - Windows build (ideally screenshot/info of `winver.exe` output): Windows 10 Version 21H2 (OS Build 19044.1826)
 - Windows' UI language: English
 - HASS.Agent version: 2022.12.0

Please check what's applicable (multiple answers possible):

 - [x] Installed via installer
 - [ ] Installed manually
 - [x] Problem occurs in HASS.Agent
 - [x] Problem occurs in Satellite Service

**Comment by LAB02-Admin** [comment]
(hopefully) fixed in the latest beta: https://github.com/LAB02-Research/HASS.Agent/releases/tag/2022.13.0-beta2

**Comment by kressir** [comment]
I am using 2022.14.0 and the retain flag is not getting set on the /state topics.  The /config topics for the same sensor do have the retain flag set.  Is this expected behavior?
