### ISSUE TITLE
Feature: Close webview automaticly after x seconds

### ISSUE THREAD

**Issue by janvanos** [LAB02-Research/HASS.Agent#129]
Is there a possibility to automaticly close the webview after a number of seconds (parameter)

I use the webview command to display my camera image on motion, so it's on top of all screens
but want to have it automaticly disappear after some time
Is there a command I can use?

**Comment by LAB02-Admin** [comment]
Not yet, but I'll add it, it's a good feature :)

**Comment by LAB02-Admin** [comment]
Closing this to keep the github list tidy, but I'll report back here when it's implemented.
