### ISSUE TITLE
Can't store LockPC command

### ISSUE THREAD

**Issue by bfish2** [LAB02-Research/HASS.Agent#13]
Thanks for creating such an awesome application!

I have tried repeatedly to add the "LockCommand".  Each time it appears to create, but when  "Store and activate commands" and then go back in to the Commands section, it is empty.  I did check on HA for the entity and it did not appear either.

**Comment by LAB02-Admin** [comment]
Yep, bug. Will fix for next version. Nice catch, thanks

**Comment by LAB02-Admin** [comment]
Fixed!

**Comment by bfish2** [comment]
Thanks!  Works great!
