### ISSUE TITLE
Bug: 'Keep page loaded in the background' impacts all Webviews, processes never close

### ISSUE THREAD

**Issue by NCopeman** [LAB02-Research/HASS.Agent#131]
If 'Keep page loaded in the background' is checked on the 'Configuration -> Tray Icon' page, any other WebViews that are opened do not correctly close. Instead, they are hidden but still appear in Task manager, as well as the alt-tab/win-tab screens. Each time a WebView command is triggered, a new process is created.

As an aside, a feature request would be the option on a per-command basis to make a webview remain loaded in the background, and return to that same process in the event the command is activated again

**Comment by LAB02-Admin** [comment]
Hey @NCopeman

Thanks for letting me know! I'll look into it :)

**Comment by LAB02-Admin** [comment]
Fixed in the latest beta: https://github.com/LAB02-Research/HASS.Agent/releases/tag/2022.13.0-beta2
