### ISSUE TITLE
Feature: hass.agent on Windows Server 2012R2

### ISSUE THREAD

**Issue by Eckart0** [LAB02-Research/HASS.Agent#133]
It seems to be impossible to install hass.agent on my Windows server. Admittedly: an old version: 2012R2
Microsoft .NET Framework 4.8 I installed, but that didn't help.
hass.agent can be installed without an error message, but then shows no configuration window and cannot be called.

Can this be changed in an upcoming version?

**Comment by LAB02-Admin** [comment]
Hey @Eckart0,

*Maybe*, I'll try to optionally disable some non-legacy compatible parts, but no guarantees :)

**Comment by LAB02-Admin** [comment]
I've implemented a user suggested fix from #113 which seems to fix it. Will be deployed in the next beta.

Follow that ticket if you want updates :)
