### ISSUE TITLE
Question: Installer

### ISSUE THREAD

**Issue by Misiu** [LAB02-Research/HASS.Agent#134]
First of all, thank You for creating such a great tool 💪
Right now I'm looking at the source code and trying to find myself in it.

I have one question about the installer: What tool did you use to create it and how did you integrate it with GitHub Actions (if it is integrated).

**Comment by LAB02-Admin** [comment]
Cheers :) 

You can find some (basic) info here:

https://hassagent.readthedocs.io/en/latest/development/introduction/
https://hassagent.readthedocs.io/en/latest/development/commands/
https://hassagent.readthedocs.io/en/latest/development/sensors/

The installer was created using Advanced Installer, it's not integrated.

**Comment by Misiu** [comment]
@LAB02-Admin thank you for such a quick reply! I'll look at the docs.
Did you use the freeware version?

**Comment by LAB02-Admin** [comment]
No, but you can just use zip packages if you want to deploy your modified version, or overwrite a current install. There are no reg changes or anything done by the installer, it just checks dotnet 6, edge runtime and then places hass.agent and the satellite binaries (doesn't even install the service, hass.agent does that).
