### ISSUE TITLE
Bug:  Scroll Lock Key Command 

### ISSUE THREAD

**Issue by danielbublil** [LAB02-Research/HASS.Agent#135]
Hi!
Great software!

**Describe the bug**
its seems that if i want to make a key command with SCROLL LOCK as key the key code always cahnging to diffreant one.

**To Reproduce**
1. create new key command.
2. at KeyCode set 0x91.
3. save and activate command.
4. open the newly created command. 
5. keycode is no longer 0x91.

i've also tried setting in decimal (145) and still not working.
other keys works fine.

**Expected behavior**

**Screenshots**

**Misc info (please complete the following information):**
 - Windows build (ideally screenshot/info of `winver.exe` output): 
 - Windows' UI language: 
 - HASS.Agent version: 

Please check what's applicable (multiple answers possible):
 - [x] Installed via installer
 - [ ] Installed manually
 - [x] Problem occurs in HASS.Agent
 - [ ] Problem occurs in Satellite Service

**Additional context**

i just wanted to press on scroll lock (i got script to change audio output).
when i use scroll lock in multiple key the key is pressed twice for some reason.

summary:
1. Scroll lock seems not working in key command.
2. Scroll lock is pressed twice in multipe key command.
3. maybe you can add a switch output device command

**Comment by LAB02-Admin** [comment]
Hey @danielbublil,

Can you please try it with the latest beta: https://github.com/LAB02-Research/HASS.Agent/releases/download/2022.13.0-beta1/HASS.Agent.Installer.exe

It should detect the keycode when you press it, and then correctly store it for you.

**Comment by danielbublil** [comment]
Hi thanks for the response!

this version is working fine, just the scroll lock led isn't toggle aswell.
which is weird.

**Comment by LAB02-Admin** [comment]
Yea scroll lock is difficult to work with, programmatically. You could try using something like [AutoHotKey](https://www.autohotkey.com) and trigger the scripts through hass.agent. I heard good things about it, haven't used it myself yet though.
