### ISSUE TITLE
Feature: AISO support

### ISSUE THREAD

**Issue by patrickiel** [LAB02-Research/HASS.Agent#138]
This is relevant for all Audio- Video Content Creators. Currently the Peak Volume is 0 when I play audio over the ASIO Protocol.

Steps to reproduce:
1. install ASIO driver https://www.asio4all.org/
2. install a free DAW https://www.reaper.fm/download.php
3. start reaper and select audio device driver, set Audio system to "ASIO", ASIO driver to "ASIO4ALL v2"
4. drag and drop audio file into reaper and play
5. check sensor value

**Comment by LAB02-Admin** [comment]
Got it, will do :)

I've created a ticket: [hassagent-133](https://lab02research.youtrack.cloud/issue/hassagent-133/). 

Closing this one to keep the github list tidy, but I'll report back here once it's done!

**Comment by patrickiel** [comment]
Awesome, thank you very much!
