### ISSUE TITLE
Feature: Webview: Open on windows startup

### ISSUE THREAD

**Issue by hell1337hound** [LAB02-Research/HASS.Agent#140]
Hi would it be possible to have an option where webview can open like a kiosk on reboot or startup

Thanks!

**Comment by LAB02-Admin** [comment]
You could do that I guess, by making a webview command, set it's size to your resolution and autohide the taskbar. Then create an automation in HA to trigger the command whenever the PC boots.

**Comment by hell1337hound** [comment]
Yep, I've done that so far but I think it would be a good option out of the box especially for Windows surfaces. Just saves having another automation

**Comment by LAB02-Admin** [comment]
I agree :) Created a ticket: [hassagent-131](https://lab02research.youtrack.cloud/issue/hassagent-131).

I'll post back here when it's implemented
