### ISSUE TITLE
Bug: main window visible on startup

### ISSUE THREAD

**Issue by patrickiel** [LAB02-Research/HASS.Agent#142]
Add the option "Minimize window at program startup" so that the window does not have to be minimized manually every time

**Comment by LAB02-Admin** [comment]
What window exactly?

**Comment by patrickiel** [comment]
That window (start-on-login is enabled)
![image](https://user-images.githubusercontent.com/86125971/184532551-99f151d0-e25a-44fb-b4fe-ebabd866b89f.png)

**Comment by LAB02-Admin** [comment]
That's weird, it shouldn't show on launch (even with start-on-login enabled). I'll see if I can find the reason

**Comment by leroyloren** [comment]
Also, would it be possible to completely disable the tray icon so that the app just runs in the background if I'm only using the remote controls?

**Comment by patrickiel** [comment]
You mean as a service? Then the application can start and stop the service? In my case I would start the application only to change the settings. The service always runs in the background.

**Comment by leroyloren** [comment]
I think, the option to hide the tray icon.

**Comment by LAB02-Admin** [comment]
@leroyloren: you can use the satellite service, and disable 'launch on login' for the agent. You won't be able to use all sensors/commands though. You can always just hide the icon in the overflow.

**Comment by LAB02-Admin** [comment]
Sorry, can't reproduce :(

**Comment by jurienhamaker** [comment]
I am having the same issue @LAB02-Admin. Every start the window shows and I have to manually hide it..
