### ISSUE TITLE
Feature: Simple Online Sensor

### ISSUE THREAD

**Issue by Daniel-dev22** [LAB02-Research/HASS.Agent#151]
Is it possible to add a simple device "online" sensor?
Obviously when offline it will not send that it's offline but home assistant would see it as offline. 

That way in home assistant I can track this specific sensor to know if the PC is on/off rather than having to say if any sensor is off it's off. This PC is on a vlan and the native home assistant ping module doesn't work for this PC even though they have access to each other.

**Comment by brainiac19** [comment]
Try template sensor maybe?
binary_sensor:
  - platform: mqtt
    name: "PC Availability"
    state_topic: "homeassistant/sensor/<your PC hostname>/availability"
    value_template: "{%if value=='online'%}ON{%else%}OFF{%endif%}"
    device_class: connectivity
