### ISSUE TITLE
Feature: Capture current screen

### ISSUE THREAD

**Issue by drjjr2** [LAB02-Research/HASS.Agent#154]
With the demise of IOTLink, one feature that it had was the current (or near current) image of each display. 

Is there a way to get the current screen shot with HASS.Agent?

**Comment by LAB02-Admin** [comment]
Not yet, but someone wrote a nice PS script you can use:

https://hassagent.readthedocs.io/en/latest/sensor-command-automation-and-script-examples/#command-grab-screenshot-using-powershell

There's a ticket for this feature, please follow it for updates:

https://lab02research.youtrack.cloud/issue/hassagent-85/Sensor-Screenshot
