### ISSUE TITLE
Feature: add stop_cover as a quick action

### ISSUE THREAD

**Issue by menuet88** [LAB02-Research/HASS.Agent#159]
Hello, I didn't find how to stop moving cover from quick actions. It looks like the stop action is not working. Is this really run service: cover.stop_cover ?
The "desired action" menu shows options like play and pause which are not for covers (or I'm wrong?). Maybe is a good idea to reduce this list to domain/service specific actions?
It is possible to check and fix cover stop action?

Best regards,
Menuet88

**Comment by Egglestron** [comment]
The logs show that it calls `media_stop` and not `cover_stop`, indeed.
Would love to see this implemented!

Cheers!

**Comment by LAB02-Admin** [comment]
Fixed in the latest beta: https://github.com/LAB02-Research/HASS.Agent/releases/tag/2022.14.0-beta1

**Comment by Egglestron** [comment]
Hmmm, the Stop action now acts as a Close action and is still labeled `media_stop` in the logs (version 2022.14.0 non beta)? Pretty weird.

**Comment by LAB02-Admin** [comment]
That is weird, worked here. I'm rewriting the entire quickactions code; it'll fetch all services/actions dynamically instead of me hardcoding them, so that should fix this and add a bunch of new stuff as well. I'll let you know when that beta is ready.

**Comment by Egglestron** [comment]
It works! Thanks. 😄
