### ISSUE TITLE
App crashes on select in taskbar

### ISSUE THREAD

**Issue by GledholtHall** [LAB02-Research/HASS.Agent#16]
Was working OK on first install but then when changed username and password to blank it crashed.  Now won't stay running, when select icon in tray it quits.  Have tried uninstall re-install but the same. Also rebooted Windows (10).  

So can't reinstall or anything.

**Comment by LAB02-Admin** [comment]
Hi @GledholtHall. What username and password do you mean? For the scheduled task?

In that case, you can run this command from an elevated command prompt:

`schtasks /delete /tn HASS.Agent`

Afterwards, open this folder in Explorer:

`%appdata%\LAB02 Research\HASS.Agent\config`

There, delete the file `appsettings.json`.

Afterwards, restart HASS.Agent and you'll start at onboarding, without losing your commands/quickactions/sensors.

Let me know if this fixes it for you :)

**Comment by GledholtHall** [comment]
It was the MQTT credential I blanked out.
Followed the above steps through onboarding but still crashed on startup.  It had retained the MQTT broker settings - I'll have a look where those are stored and try deleting that prefs file too.

**Comment by LAB02-Admin** [comment]
The MQTT credentials are definitely stored in `appsettings.json`. Can you please look if there's anything in the logs, and if so, send me the content (please remove any credentials)? They're in `%appdata%\LAB02 Research\HASS.Agent\logs`.

**Comment by LAB02-Admin** [comment]
I'm closing the ticket as it's solved, but if you do find anything interesting in the logs, please let me know :)
