### ISSUE TITLE
Bug: mqtt not connecting correctly

### ISSUE THREAD

**Issue by NopeFinder** [LAB02-Research/HASS.Agent#161]
Please make sure your bug isn't already listed on HASS.Agent's issue tracker:

https://lab02research.youtrack.cloud/

There's a list of open bugs & features on the right. On the left you can see what's being worked on, what's planned and what's ready for the next release.

If you're not sure, don't worry, just go ahead and we'll discuss :)

----

**Describe the bug**
It appears hass.agent is not sending the login to my mosquitto mqtt broker on home assistant. I keep getting the message:
"2022-09-12 21:36:24: Client <unknown> disconnected, not authorised.
2022-09-12 21:36:29: New connection from 192.168.0.49:53002 on port 1883.
error: received null username or password for unpwd check"
every 5 seconds.

**To Reproduce**
install hass.agent and set up mqtt

**Expected behavior**
mqtt communication with the broker

**Screenshots**
![Screenshot 2022-09-12 211956](https://user-images.githubusercontent.com/45026256/189742110-1b4bc6b6-c068-4b3d-a940-5932147b9df3.png)
![Screenshot 2022-09-12 212040](https://user-images.githubusercontent.com/45026256/189742122-231e7839-12a8-4018-bb3f-7d06eefd5929.png)

**Misc info (please complete the following information):**
 - Windows build (ideally screenshot/info of `winver.exe` output):  
![Screenshot 2022-09-12 214641](https://user-images.githubusercontent.com/45026256/189742354-cfba62b2-82b0-46e1-8582-76b26b109e39.png)
 - Windows' UI language: English
 - HASS.Agent version: [2022.12.0] and [2022.13.0-beta2]

Please check what's applicable (multiple answers possible):

 - [x] Installed via installer
 - [ ] Installed manually
 - [x] Problem occurs in HASS.Agent
 - [x ] Problem occurs in Satellite Service

**Additional context**

**Logs**
If possible, please provide the logs of HASS.Agent and - if applicable - the Satellite Service. You can find HASS.Agent's logs by going to the main window, then `Configuration` -> `Logging` -> `open logs folder`. The Satellite Service's logs are in the same window, but the `Satellite Service` tab -> `open service logs folder`. If you want, you can mail them to lab02research@outlook.com

**Comment by NopeFinder** [comment]
fixed it, i added 127.0.0.1 and ::1 to my trusted_proxies in my config file and now it works. Hadn't added them yet as i was only using mqtt for rhasspy so far and that uses an private ip starting with 172.

**Comment by LAB02-Admin** [comment]
Nice find! Glad it's fixed

**Comment by alexschwantes** [comment]
@NopeFinder can you clarify how you fixed this? I am getting the exact same thing with the same setup

**Comment by alexschwantes** [comment]
Ok I figured it out actually, it is the HASS.Agent Satellite Service. that was continually trying to connect to MQTT broker without any credentials. Apparently you have to set this up separately from the MQTT settings in HASS.Agent.

@LAB02-Admin perhaps it would be nice feature request to show this issue in the system status for the satellite service, as it was always reading 'ok' despite not being able to connect to MQTT..

**Comment by LAB02-Admin** [comment]
@alexschwantes next version will sync hass.agent's mqtt settings to the service (except the client id), but good point on the issue status, will do :)
