### ISSUE TITLE
MQTT not connecting suddenly

### ISSUE THREAD

**Issue by bfish2** [LAB02-Research/HASS.Agent#162]
As of sometime today, MQTT is not connecting to HASS.Agent thus rendering a number of my automations inactive.  It is mainly in "Connecting" but sometimes flashes yellow "Stopped" for a second or two, then returns to "Connecting."  See picture below...

I did notice two things:  My PC did Win10 updates and I did see HA update to 2022.9.3 was released so I applied that (both after this issue began).

I have double checked MQTT user logins, etc. and nothing changed.

Any thoughts?

![image](https://user-images.githubusercontent.com/70775126/190051981-561343f0-fa25-45a3-8f10-dd1ef579da6e.png)

**Comment by bfish2** [comment]
Just discovered two errors in HASS logs:

Platform mqtt does not generate unique IDs. ID 69aad1a4-9c9e-4db9-990d-22b720d22b19 already exists - ignoring switch.restart_bt_pc

12:28:48 PM – (ERROR) Switch
Platform mqtt does not generate unique IDs. ID 7043d1b6-17dd-427e-ab1e-29e694047b64 already exists - ignoring sensor.shs_brad_sessionstate
12:28:48 PM – (ERROR) Sensor

**Comment by bfish2** [comment]
When I tried to delete that command (Restart_BT_PC) then "Store and Activate"  it just hangs there and won't finish.

![image](https://user-images.githubusercontent.com/70775126/190631340-bfe0b165-b071-4ca3-aad1-4ba7a2bf8b4f.png)

As for broker logs, i never see any, just this:

![image](https://user-images.githubusercontent.com/70775126/190631492-092819ae-d5b8-49af-a088-0137805a1f14.png)

**Comment by LAB02-Admin** [comment]
Hm that makes sense I guess, since it can't unregister on MQTT. Do that when this problem is fixed, it's not pressing anyway.

Can you connect with HASS.Agent's credentials using a MQTT client app like MQTT Explorer?

**Comment by LAB02-Admin** [comment]
Okay, so something's up with the broker's configuration. You use the mosquitto addon for that right? And the logs aren't showing anything at all? 

To make sure: is the addon started? I had an issue a while back with addons not starting anymore after a HA update.

**Comment by bfish2** [comment]
I just checked and the broker was running.  I uninstalled it and reinstalled it, but to no avail.

I'm not sure what else to check as I only use Mosquitto for Hass.agent and haven't made any changes, other than upgrading HA versions.

**Comment by bfish2** [comment]
OK, deleted both broker and integration, rebooted HA, and reloaded both and now seem to be working.  Not sure what was going on, but I appear to be back in business now.  Thanks for your help in pointing me in the right directions.
