### ISSUE TITLE
Cannot run

### ISSUE THREAD

**Issue by TrustedFloppa** [LAB02-Research/HASS.Agent#163]
After i completed installation it returns with error.
(I have .NET 6.0.6 Installed)
![image](https://user-images.githubusercontent.com/85476585/190361853-b0ea3937-6edc-4dc4-b94d-428a84332685.png)

**Comment by LAB02-Admin** [comment]
Do you have the desktop runtime installed as well? It differs from the 'regular' .NET 6.

**Comment by TrustedFloppa** [comment]
Yeah I have

**Comment by LAB02-Admin** [comment]
Then I don't know. To make sure; did you restart your device?

Try running `sfc /scannow` and optionally `dism /online /cleanup-image /restorehealth` to fix system files, sounds like something's broken.

**Comment by TrustedFloppa** [comment]
It was broken because it returned with error

**Comment by LAB02-Admin** [comment]
Did you run dism as well? If you run sfc again, does it still give an error?

**Comment by TrustedFloppa** [comment]
It returned with corruption error I also runned dism but it can't fix it

**Comment by LAB02-Admin** [comment]
Too bad :( I'm sorry but that's beyond the scope of HASS.Agent to fix. You can make sure your Windows is fully patched & up-to-date. Otherwise you could consult a Windows helpforum to assist you.

**Comment by TrustedFloppa** [comment]
Yea I have installed

**Comment by TrustedFloppa** [comment]
I fixed the error with reinstalling .NET and hass.agent started working
