### ISSUE TITLE
Feature: On Off Commands for Switch

### ISSUE THREAD

**Issue by n0tOdd** [LAB02-Research/HASS.Agent#164]
Would it be possible to get a custom command to be run when turning off the switch?
like say i want one switch for bluetooth so i can turn it on and off whit the same switch instead of one button for on and another for off

If its already integrated and i just cant find it, im sorry for wasting youre time

**Comment by LAB02-Admin** [comment]
Hm not directly, you could create an automation in HA that runs the command when the switch turns off.
