### ISSUE TITLE
Feature: CPU temperature

### ISSUE THREAD

**Issue by NickyMB** [LAB02-Research/HASS.Agent#165]
I want to be able to see CPU temperature in homeassistant dashboard, something like GPU temperature

**Comment by LAB02-Admin** [comment]
It'll be integrated in the future, but for now you can use openhardwaremonitor and WMI sensors:

https://hassagent.readthedocs.io/en/latest/wmi-examples/#fetch-cpu-temp-from-openhardwaremonitor

**Comment by LAB02-Admin** [comment]
You can follow the implementation's progress here: [hassagent-9](https://lab02research.youtrack.cloud/issue/hassagent-9)
