### ISSUE TITLE
Misc: Issue with new installation

### ISSUE THREAD

**Issue by jakenocera** [LAB02-Research/HASS.Agent#166]
Hey Folks-
New install seems to mostly work. MQTT is being sent and received by HA. I am able to load my entities, and control them from HASS.AGENT which is all great. 
I have MQTT discovery turned on, but for some reason, the entities are not auto creating for the local sensors I created.

Any thoughts are greatly appreciated.

Jake
----

**Comment by LAB02-Admin** [comment]
If you're not running the beta; do you have a space in your device's name?

**Comment by LAB02-Admin** [comment]
Closed as stale, let me know if you still need help
