### ISSUE TITLE
Feature: Printer Job sensor

### ISSUE THREAD

**Issue by Diddlik** [LAB02-Research/HASS.Agent#169]
A sensor that indicates whether a printer job is present would be desirable. Possibly also the name of the job, but a true/false to the job is already good enough.
Thus one can make automation, which switches the printer on, if a printer job is present.

**Comment by LAB02-Admin** [comment]
Hey @Diddlik, that's already present in the beta branch: https://github.com/LAB02-Research/HASS.Agent/releases/tag/2022.13.0-beta3

From beta 2's release notes:



>New multivalue sensor: Printers
>
>   Provides information about all installed (usb and network) printers and their queues
>   Creates a sensor per printer, with its state as attributes
>   Also creates a sensor for the default printer ('queue') and the amount of pending prints

**Comment by Diddlik** [comment]
This is fine, just download installer and install as update?
