### ISSUE TITLE
Bug: Sessionstate no longer working after Windows Update

### ISSUE THREAD

**Issue by vidarak** [LAB02-Research/HASS.Agent#171]
**Describe the bug**
After installing Win11 21H2 (OS Build 22000.1042) the session state sensor became unavailable/unknown. 

**To Reproduce**
1. Go to 'sensors config'
2. Click on 'add new'
3. Scroll down to 'SessionState'
4. Click on 'store sensor'
5. Click on store and activate sensors
6. Go to 'sensors config'
7. Inspect the last known value of the SessionState sensor..... being 'Unknown'

**Expected behavior**
It should have had the state of Locked/Unlocked like before.

**Screenshots**
![image](https://user-images.githubusercontent.com/4713602/191932559-a2d19899-cb50-4077-ba43-1f0f3e5ab1b3.png)

**Misc info (please complete the following information):**
 - Windows build (ideally screenshot/info of `winver.exe` output): 
 - 
![image](https://user-images.githubusercontent.com/4713602/191932645-47f1f8c8-689f-40c8-a1b3-03a06cafd788.png)

 - Windows' UI language: English
 - HASS.Agent version: 2022.12 and 2022.13-beta3

Please check what's applicable (multiple answers possible):

 - [x] Installed via installer
 - [ ] Installed manually
 - [x] Problem occurs in HASS.Agent
 - [ ] Problem occurs in Satellite Service

**Additional context**
I worked around it by creating a processactive sensor looking for "logonui" process which returns 0 when unlocked and 1 when locked.

**Logs**
2022-09-23 10:35:38.210 +02:00 [FTL] [SENSORTESTER] Error while testing WMI query
Scope: \\localhost\
Query: Get-WmiObject -Class Win32_ComputerSystem -ComputerName $Computer | Select-Object -ExpandProperty UserName -ErrorAction Stop
Error: Invalid query 
System.Management.ManagementException: Invalid query 
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   at HASS.Agent.Shared.HomeAssistant.Sensors.WmiQuerySensor.GetState()
   at HASS.Agent.Functions.SensorTester.TestWmiQuery(String query, String scope)

**Comment by LAB02-Admin** [comment]
Weird. Just to be sure; did you reboot after creating the sensor?

About your error log: that's a powershell query you're trying on a wmi sensor. You can create the wmi sensor with the following query:

`SELECT UserName FROM Win32_ComputerSystem WHERE Name='your-device-name'`

Keep wmi scope empty.

**Comment by vidarak** [comment]
I have had the sensor working for a long time. Yesterday I applied the latest Windows Update and did a reboot. Afterwards it hasn't worked. I have reinstalled HASS.Agent etc without any improvement.

The WMI object UserName is gone from Win32_ComputerSystem now.
![image](https://user-images.githubusercontent.com/4713602/191947244-5c914041-cbed-4e47-8d64-e1f939a66010.png)

**Comment by LAB02-Admin** [comment]
Hm weird, I'll setup a test environment with that update.

You're using `\\localhost\` as a scope, but that should be `\\.\ROOT\`. You can keep the 'scope` empty if you want, HASS.Agent will default to that root scope.

**Comment by vidarak** [comment]
In my case i did leave it empty and it defaulted to \\localhost

![image](https://user-images.githubusercontent.com/4713602/191951328-b57f9b2b-705f-4231-bf49-22b2af4786f3.png)

This command:
get-wmiobject -Class win32_computersystem
... does no longer provide the UserName property.

**Comment by LAB02-Admin** [comment]
Weird stuff again.

I just checked, and apparently I have the exact same Windows build as you. The WMI query works here, and the SessionState sensor as well. So something else seems wrong :\

This PS script works as well: `Get-WmiObject -Class Win32_ComputerSystem -ComputerName pc_name| Select-Object -ExpandProperty UserName`

Do you know how to use WMI Explorer tool? Could you try browse to the properties manually?

**Comment by vidarak** [comment]
![image](https://user-images.githubusercontent.com/4713602/191955457-b47e0741-e473-4fab-b99a-d977f471dbb7.png)

**Comment by LAB02-Admin** [comment]
That just means it's not 'enumerable', ie. it doesn't have a set of predetermined values. For instance, the `BootupState` property has these enumeration values: 

       Normal boot
       Fail-safe boot
       Fail-safe with network boot

Could you please click `Execute` in the bottom right of that screen. You should get one result, with a bunch of values. If you scroll to the right of that list, do you see a UserName value:

![image](https://user-images.githubusercontent.com/81011038/191956991-79cf527c-a7cb-4d9e-867d-f81dff391424.png)

**Comment by vidarak** [comment]
In Data Grid view I see the UserName property with an empty value field.
In List View there is no UserName propertly listed.

**Comment by vidarak** [comment]
I rebooted again to make sure... and it now shows my username on the WMI object + the sessionstate works again... showing unlocked/locked.....
