### ISSUE TITLE
Bug: Install issue does not complete with Windows7

### ISSUE THREAD

**Issue by Zilla31** [LAB02-Research/HASS.Agent#173]
Hello,

Using Windows 7, I can not find if this version is compatible with HASS.Agent.
So far, I run the install but it terminzte after the HASS agent files  are getting Installed without any further notification and does not access the following configuration steps.
I can find HASS agent is at the correct directory Users\XXXX\AppData\Roaming\LAB02 Research\HASS.Agent but the agent does not execute when selected.
I hav run few times the repair/modify or delete and re-install but I am always going into the same trouble.

Any idea what is going wrong with the install?

Thanks

Zilla

**Comment by LAB02-Admin** [comment]
You can try using the latest beta: https://github.com/LAB02-Research/HASS.Agent/releases/tag/2022.13.0-beta3

**Comment by Zilla31** [comment]
Thanks. I could get through the configuration process and execute the HASS agent. This Beta did not solve my issue!

**Comment by LAB02-Admin** [comment]
Unfortunately Windows 7 isn't really supported. If it doesn't launch on your system then there's not much I can do.

You could try the last .NET 4.8 version:

https://github.com/LAB02-Research/HASS.Agent/releases/tag/v2022.3.8

**Comment by Zilla31** [comment]
Sorry, I made a fatal typo at the end of my response. This Beta did ACTUALLY solve my issue!

So far, it seems to work OK with Windows7 for integrating the commands, hot key, quick actions and sensors. I think only the Notification fails with Windows7 as Windows 7 are limited to those little pop-up notification.

I can still enjoy a lot of the functionalities of the HASS_agent

**Comment by LAB02-Admin** [comment]
Oh, really glad to hear that! I'm planning on implementing my own notification system (because Windows' version gives too many limitations/complexities) so by then you should be able to use those as well :)

Thanks for letting me know

**Comment by Zilla31** [comment]
Really impressive tool.

My first project will be to use it as my own parental control tool with auto and manual routine :) My kids are not going to like ithis app as I do... I maycome back with more questions!

Have a good day !
