### ISSUE TITLE
Bug: MQTT won't connect

### ISSUE THREAD

**Issue by Kedryn** [LAB02-Research/HASS.Agent#175]
**Describe the bug**
Just installed  and configured. HA connection works ok, MQTT not.

From HA Logs:
2022-09-28 14:19:14: New connection from 172.30.32.1:52336 on port 1883.
error: received null username or password for unpwd check

User and Password for MQTT in HASS.Agent are fine. No SSL.

**Expected behavior**
MQTT connects

**Screenshots**
![image](https://user-images.githubusercontent.com/12759632/192777982-247b52cb-d80b-4caa-adfc-d8e1845db107.png)

**Misc info (please complete the following information):**
 - Windows build (ideally screenshot/info of `winver.exe` output): 
 
![image](https://user-images.githubusercontent.com/12759632/192778357-414ade42-6ccd-47c7-a10a-5ffd525140e7.png)

 - Windows' UI language: Italian
 - HASS.Agent version: 2022.12.0

Please check what's applicable (multiple answers possible):

 - [x] Installed via installer
 - [ ] Installed manually
 - [x] Problem occurs in HASS.Agent
 - [ ] Problem occurs in Satellite Service

**Logs**

Mailed

**Comment by LAB02-Admin** [comment]
Well there are a lot of connection problems here. At first it states that the username/password isn't right, and afterwards it's having trouble building the connection. Can you post a screenshot of your hass.agent mqtt configuration? And have you tried that same config with mqtt explorer?

**Comment by LAB02-Admin** [comment]
Closing this as stale, let me know if you still need help
