### ISSUE TITLE
Feature: Bluetooth battery info

### ISSUE THREAD

**Issue by bkbilly** [LAB02-Research/HASS.Agent#176]
Get information about connected bluetooth devices and their battery:

![image](https://user-images.githubusercontent.com/518494/193678458-bbe2bf96-f134-4f86-8636-3e5771ad9f99.png)

This might be useful: https://learn.microsoft.com/en-us/windows/uwp/devices-sensors/get-battery-info

**Comment by LAB02-Admin** [comment]
Hi @bkbilly,

The latest beta has bluetooth sensors: https://github.com/LAB02-Research/HASS.Agent/releases/tag/2022.13.0-beta4

But no support for battery yet, I'll look into it :)

**Comment by bkbilly** [comment]
I've looked into it, and I couldn't find a way to check the bluetooth battery through C#.

I've found another way that this might be able to be implemented, using PowerShell commands:
https://stackoverflow.com/questions/71736070/how-to-get-bluetooth-device-battery-percentage-using-powershell-on-windows

**Comment by bkbilly** [comment]
With the new version of 2022.13.0 and the new PowerShellSensor I created a new sensor with the following command:
```powershell
(Get-PnpDevice -Class 'Bluetooth' -FriendlyName ''Xbox Wireless Controller' | Get-PnpDeviceProperty -KeyName '{104EA319-6EE2-4701-BD47-8DDBF425BBE5} 2').Data
```
Then, I modified on Home Assistant [customize](https://www.home-assistant.io/docs/configuration/customizing-devices/#manual-customization) like so:
```yaml
sensor.desktop_windows_xboxbattery:
  device_class: battery
```
Restarted everything and now I have the battery percentage of my device.
