### ISSUE TITLE
300% Scaling @ 4K Renders UI Useless

### ISSUE THREAD

**Issue by Apocrathia** [LAB02-Research/HASS.Agent#178]
I've install HASS.Agent on my PC in my living room, as IoTLink has been discontinued. However, I am using a 300% scaling on a 4k screen, and this is how my application looks...
Welcome screen
![image](https://user-images.githubusercontent.com/1345711/194727066-983c97bf-d63e-4924-b232-b1209da54380.png)
Taskbar context menu
![image](https://user-images.githubusercontent.com/1345711/194727085-96633614-7bed-46ea-b535-628e730484db.png)
Configuration screen
![image](https://user-images.githubusercontent.com/1345711/194727103-f51ea7dc-7b8c-4c76-b6b6-063431b99dcc.png)

I'm going to drop down to 1080p so that I can get everything configured, but I'm really hoping I don't have to go back and change anything. All I really need is system stats reported to HA.

**Comment by LAB02-Admin** [comment]
Yea that is messed up.. Could you please try this beta, it has (somewhat) improved DPI handling:

https://github.com/LAB02-Research/HASS.Agent/releases/download/2022.13.0-beta2/HASS.Agent.Installer.exe

**Comment by Apocrathia** [comment]
Much better!
![image](https://user-images.githubusercontent.com/1345711/195145536-6ec77243-93a4-423a-a93d-ebad72d9fc24.png)

It looks like the changes mentioned in #99 were effective. I've gone ahead and updated to beta4 and it also looks fine now.
![image](https://user-images.githubusercontent.com/1345711/195147436-f6b13416-24fc-4ec0-ad2e-f177c0c67712.png)

I'll go ahead and close this issue, as it looks like the next release will resolve the UI scaling issues.
