### ISSUE TITLE
Media Player won't start

### ISSUE THREAD

**Issue by Bollemp3** [LAB02-Research/HASS.Agent#180]
Hi, 

I'm using the Beta-4 now because i had some install issues. 
Those issues are gone now 👍 

The only thing that left is the media player won't start.
Is it because i'm using a (old) USB audio device official not supported by Win10?

The log is telling me:

2022-10-11 07:08:16.345 +02:00 [ERR] [PROGRAM] FileNotFoundException: Kan opgegeven module niet vinden. (0x8007007E)
2022-10-11 07:08:18.047 +02:00 [ERR] [MEDIA] Unable to initialize, your OS doesn't seem to be supported or isn't fully updated:
The type initializer for 'WinRT.ActivationFactory`1' threw an exception.
2022-10-11 07:08:18.047 +02:00 [WRN] [MEDIA] Failed, disabled

Sorry guys for the dutch installation on my system :)

THANKS FOR THIS GREAT PRODUCT!!!

**Comment by LAB02-Admin** [comment]
Hi @Bollemp3, no doesn't seem to be related to the actual device, but it looks like your Windows version isn't up to date. The mediaplayer requires a fairly uptodate system, don't really know exactly what version of W10 though.

Yw!

**Comment by Bollemp3** [comment]
Hi Yw,

Just checed my updates but windows is updated.

My Windows specs are:
Editie	Windows 10 Pro N for Workstations
Versie	20H2
Installatiedatum	‎10-‎10-‎2022
Build van besturingssysteem	19042.2006
Ervaring	Windows Feature Experience Pack 120.2212.4180.0

Bollemp3

**Comment by LAB02-Admin** [comment]
According to [this link](https://support.microsoft.com/en-us/topic/media-feature-pack-for-n-editions-of-windows-10-version-1607-b657cb70-33e7-1f11-7119-3b4b50be4e89#:~:text=The%20%22N%22%20editions%20of%20Windows,,%20Video,%20Voice%20Recorder):

> The "N" editions of Windows 10 include the same functionality as other editions of Windows 10 except for media-related technologies. 

So you can try installing the package at the bottom of that page:

http://www.microsoft.com/download/details.aspx?familyid=aee1c16a-373a-4249-bbe9-4284b779f9c1

Reboot, and then try again.

**Comment by Bollemp3** [comment]
Hi,

OOO Damned my mistake :( Thanks :D
BTW: The link doesn't work for this version ;)

But this is much easier:

On Windows 10 N: Select the Start button, then select Settings > Apps > 
Apps and Features > Optional features > Add a feature. Find the Media 
Feature Pack in the list of available optional features

THNX Guy's!

Bollemp3

LAB02 Research | Sam schreef op 2022-10-12 14:00:

**Comment by LAB02-Admin** [comment]
Great! You're welcome :)
