### ISSUE TITLE
Feature: Ability to Backup/import hass agent configs

### ISSUE THREAD

**Issue by eddyliao** [LAB02-Research/HASS.Agent#181]
Hi, Amazing software, it would be cool to have a way to import/export Hass agent config to other instances/pc
Bonus if we could store it on cloud instances like a google drive, tho not required

**Comment by LAB02-Admin** [comment]
Agreed, it's on the todo list: [hassagent-12](https://lab02research.youtrack.cloud/issue/hassagent-12)

**Comment by rEs-84** [comment]
2nd this.
i setup the normal instance, then noticed its just the satellite service i needed to configure for my needs.

**Comment by LAB02-Admin** [comment]
I'm closing this ticket (since it's already open) to avoid clutter, but it's being worked on :)
