### ISSUE TITLE
Bug: Webview opens a new window every time 

### ISSUE THREAD

**Issue by Zenchyi1** [LAB02-Research/HASS.Agent#182]
**Describe the bug**
Webview spawns a windows thats not viewable in the taskbar, nor can i close it. but when i win+tab (NOT ALT-TAB) then every single webview window that i ever opened comes up.

**To Reproduce**
1. Create command for webview 
2. assign command to hotkey
3. use said command to spawn window

**Expected behavior**
It closes immediatly and gets rid of any traces. 

**Screenshots**
![image](https://user-images.githubusercontent.com/107559945/195390296-0c7c5026-3a8d-4fc2-8187-26ded27ae241.png)
![image](https://user-images.githubusercontent.com/107559945/195390568-6282ce5b-39de-426e-9eb3-4e91d81cc644.png)

**Misc info (please complete the following information):**
 - Windows build: 
![image](https://user-images.githubusercontent.com/107559945/195391220-c108b5bf-d670-4a09-859e-8cf74886ad15.png)

 - Windows' UI language: English
 - HASS.Agent version: 2022.12.0

Please check what's applicable (multiple answers possible):

 - [x] Installed via installer
 - [ ] Installed manually
 - [x] Problem occurs in HASS.Agent
 - [ ] Problem occurs in Satellite Service

**Additional context**
-

**Logs**
Nothing about the webview, other than that it stored the quick action hotkey for it.

**Comment by LAB02-Admin** [comment]
Hi @Zenchyi1,

As artsy as that looks, that shouldn't happen. I've improved the webview code in the upcoming version, one of the bugs was indeed that old webviews wouldn't close, so hopefully that'll fix this as well. 

Should get released this weekend, let me know if it persists afterwards!

**Comment by LAB02-Admin** [comment]
Should be fixed in the latest release: [2022.13.0](https://github.com/LAB02-Research/HASS.Agent/releases/tag/2022.13.0)
