### ISSUE TITLE
Misc: x86 Support

### ISSUE THREAD

**Issue by onexey** [LAB02-Research/HASS.Agent#188]
Hi,

I am trying to include an old x86 Windows tablet in my home automation system. But the application targeted to the x64. Is there any specific reason the project only targeted x64 architecture? I tried compiling from the source code but for some reason, exe does nothing on the client. I just wanted to ask you before trying to troubleshoot.

**Comment by LAB02-Admin** [comment]
Hi @onexey,

I don't remember exactly since it's been over a year ago that I decided to go for x64, but I think it was because of a library that requires specification. 

I'll see if I can make some time this weekend to compile for x86

**Comment by LAB02-Admin** [comment]
I've created a quick build as 'anycpu', which should *in theory* work on x86, could you try it out:

https://shares.lab02-research.org//tests/onexey/hass.agent.zip

It works here, but since I have a x64 cpu, I can't be sure. 

If it fails to start, I'll make a x86 VM so I can test a bit better - so in that case, what OS/build are you running on the tablet? You can easily check by running winver.exe.

**Comment by onexey** [comment]
That was quick :)

Unfortunately, it didn't work. This is the SS of the error.
![image](https://user-images.githubusercontent.com/1856335/197252685-be513d3d-88a6-4d4a-894d-291935d92271.png)


The OS is Windows 10 21H2 (19044.2130) Home Single Language
The CPU in this tablet is Intel Atom Z3735F. Even though CPU is technically x64 capable, for some reason the thing won't let me install any x64 OS on it.

Does the installer only install this? Is there any specific build process you got? Maybe I can try and troubleshoot as well.

**Comment by LAB02-Admin** [comment]
> Does the installer only install this? 

Basically yea, it also places the satellite service in programfiles but let's focus on getting this to work first. It also launches hass.agent with a `postupdate` argument so it configures the local api.

> Is there any specific build process you got? 

Only for releases, but that's for signing, otherwise no.

You can use this repo to easily build and test yourself: https://github.com/LAB02-Research/HASS.Agent.Staging

It includes the shared library.

**Comment by onexey** [comment]
OK, A little update. It's working now.

Here are the steps I took:
- Set the platform target to "Any CPU"
- Set the target runtime "win-x86"

With these settings, I received an error saying "you need to install dotnet core 6.0.0" even though I already installed the latest dotnet core 6.0.X version. I also tried installing dotnet core 6.0.0 version, but no luck.

So I tried these steps:
- Set the platform target to "Any CPU"
- Set the target runtime "win-x86"
- Set the deployment mode "Self-contained"

This worked without a problem. Completed the installation wizard with this build.

After that, I tried again with the "Framework-dependent" build so I can troubleshoot. But now that build works as well :) (Although now it doesn't bring the wizard. It directly opens the agent itself.) So I don't know if it's related to some problem with the wizard or windows itself.

Anyway here is my now working build profile:
![image](https://user-images.githubusercontent.com/1856335/197338546-646aff2c-3ab9-4bf5-aadd-0ec14fc9e645.png)

Currently only the "satellite service" not working because basically it's not installed. I'll try to build that and update you with my findings.

**Comment by LAB02-Admin** [comment]
Awesome! Self contained is always a nice solution.

>  (Although now it doesn't bring the wizard. It directly opens the agent itself.) So I don't know if it's related to some problem with the wizard or windows itself.

That's because it only shows once. If you want to show it again, delete appsettings.json.

> Currently only the "satellite service" not working because basically it's not installed. 

You can create a self contained version, and place it in `C:\Program Files (x86)\LAB02 Research\HASS.Agent Satellite Service`. Then launch HASS.Agent from an elevated commandprompt as such: `HASS.Agent.exe update`. It'll register and launch the service.

**Comment by onexey** [comment]
Thank you for that info. Probably saved me a lot of trial and error :)

I didn't try every single function but the program looks like working without a problem.

Also thank you for the program itself. Made my life a lot easier :)

**Comment by tmikoss** [comment]
Sorry to stir up a closed issue, but I'm curious:

> it's been over a year ago that I decided to go for x64

Is there a particular version of hass.agent that would be the latest 32bit release? I would be very much fine with running that, especially if it still focuses on the now "legacy" HTTP API instead of MQTT. My goal is to get the sensor readings off of an older 32-bit only Windows tablet.

Building the "normal" projects with x86 target did not work, and while the staging project did compile and install, I'm getting weird errors and UI hangups, indicating to me that something is not quite right.

**Comment by LAB02-Admin** [comment]
Hey @tmikoss,

It's because everything's moving towards x64 (Windows 11 doesn't even have a 32bit release). Since it's a spare-time project, and I'm the only dev, I have to manage my time accordingly. There are also some performance improvements in x64, although I suspect the impact's minimal for this project.

That said, I'll write a manual on the docs on how to compile for x86.

**Comment by gonzasmts** [comment]
hey @onexey and @LAB02-Admin , sorry for posting on an old issue, but i'm trying to follow the previous instructions to build an x86 version but without success.

a bit of context, i have one table with one Atom cpu (x64) but the windows home is x86 locked by bios, and i was thinking on using it as a wall panel.

when i build the app for x86 and try it on the tablet, it just doesn't open, nothing happen.

so far i try to build da app on the tablet itself using the command line, and tried on my main pc but the result is the same, nothing happen on the tablet when i run HASS.Agent.exe, i did use the main repo to build.

thanks

**Comment by onexey** [comment]
Hi, @gonzasmts. Sorry for the late response.

From what I remember the last time, It took some time for the program actually appear (Slow tablet). So I can suggest a clear restart before opening the application. So previous runs or other programs won't affect as much.

I can't remember if I did any cleanup before my successful run, but maybe it can be another troubleshooting step for you. Just try and make sure previous attempts didn't leave any config/cache files to interfere with.

Hope this helps :)

**Comment by gonzasmts** [comment]
Hi @onexey, just to give you some feedback on this, your build works just fine, but for some reason mine don't, i tried with Self-contained:
![image](https://user-images.githubusercontent.com/52658572/218138502-b1de046f-62cd-44c9-9a45-fb236c06ad3a.png)
and with framework-dependent
![image](https://user-images.githubusercontent.com/52658572/218138677-9472a2af-55bd-44a5-b760-b2970f3e8b8e.png)

also in the configuration i changed to this: <PlatformTarget>AnyCPU</PlatformTarget>
but none of those options open, and i don't know if i'm missing something or not...

i'm ok with using your version, but if i can't build it i will not be able to update it in the future.
thanks for your help

**Comment by onexey** [comment]
Did you also change the target framework of `HASS.Agent.Shared` project?
I just checked my [fork](https://github.com/LAB02-Research/HASS.Agent.Staging/compare/main...onexey:HASS.Agent.Staging:main) again and realized I changed the target architecture for both projects.

The code in that repo is the same as my local machine. Maybe you could try that one to see if it works.

**Comment by gonzasmts** [comment]
no, i was building only the Hass.Agent project.
i will try that and will let you know

thanks

**Comment by Ouxipi** [comment]
> @onexey非常感谢，已经构建了当前版本，它正在我的旧 x86 平板电脑上运行:-)

我目前有一个z3736F核心的win10 32位平板 但是官方只能下载x64位的  能否提供一份您在x86上使用的文件 十分谢谢

At present, I have a win10 32-bit tablet with z3736F core, but the official download can only be x64 bit. Could you please provide a file for you to use on x86? Thank you very much

**Comment by Ouxipi** [comment]
> 您是否也更改了项目的目标框架`HASS.Agent.Shared`？ 我刚刚再次检查了我的[分叉](https://github.com/LAB02-Research/HASS.Agent.Staging/compare/main...onexey:HASS.Agent.Staging:main)，意识到我更改了两个项目的目标架构。
> 
> 该存储库中的代码与我的本地计算机相同。也许你可以尝试一下，看看是否有效。

At present, I have a win10 32-bit tablet with z3736F core, but the official download can only be x64 bit. Could you please provide a file for you to use on x86? Thank you very much

**Comment by onexey** [comment]
> > 您是否也更改了项目的目标框架`HASS.Agent.Shared`？ 我刚刚再次检查了我的[分叉](https://github.com/LAB02-Research/HASS.Agent.Staging/compare/main...onexey:HASS.Agent.Staging:main)，意识到我更改了两个项目的目标架构。
> > 该存储库中的代码与我的本地计算机相同。也许你可以尝试一下，看看是否有效。
> 
> At present, I have a win10 32-bit tablet with z3736F core, but the official download can only be x64 bit. Could you please provide a file for you to use on x86? Thank you very much

Unfortunately, my tablet decided not to work anymore, so I no longer have a test environment. All I can provide at the moment is the old [fork](https://github.com/onexey/HASS.Agent.Staging) I have.

**Comment by LucasTor** [comment]
I am trying to run it in an x86 environment as well, by any chance do any of you guys have the compiled x86 version? I am not very familiar with Visual Studio and .NET

**Comment by andreitrinidad** [comment]
@popy2k14 can you provide your .exe file?

**Comment by popy2k14** [comment]
Sorry guys, i dont have the x86 tablet and sadly also cant find the build anymore.

**Comment by alexit190** [comment]
> OK, A little update. It's working now.
> 
> Here are the steps I took:
> 
> * Set the platform target to "Any CPU"
> * Set the target runtime "win-x86"
> 
> With these settings, I received an error saying "you need to install dotnet core 6.0.0" even though I already installed the latest dotnet core 6.0.X version. I also tried installing dotnet core 6.0.0 version, but no luck.
> 
> So I tried these steps:
> 
> * Set the platform target to "Any CPU"
> * Set the target runtime "win-x86"
> * Set the deployment mode "Self-contained"
> 
> This worked without a problem. Completed the installation wizard with this build.
> 
> After that, I tried again with the "Framework-dependent" build so I can troubleshoot. But now that build works as well :) (Although now it doesn't bring the wizard. It directly opens the agent itself.) So I don't know if it's related to some problem with the wizard or windows itself.
> 
> Anyway here is my now working build profile: ![image](https://user-images.githubusercontent.com/1856335/197338546-646aff2c-3ab9-4bf5-aadd-0ec14fc9e645.png)
> 
> Currently only the "satellite service" not working because basically it's not installed. I'll try to build that and update you with my findings.

Hi, I'm trying to make 32bit build, I managed to configure the build and even made a build, but for some reason when I run the application on 32bit win10 it does not start at all - the application window does not appear and the process closes in about 5 sec.
I cannot find any logs in the application folder, can you help me?
PS. This build is started successfully on 64bit OS
