### ISSUE TITLE
Sending function keys

### ISSUE THREAD

**Issue by Protoncek** [LAB02-Research/HASS.Agent#189]
Hello!

First: congrats for this great program! I'm just at very start of learning and it's ...just great!
However, i already have first question: I'd like to create a command to send F5 (refresh web page) from HA to my laptop. I managed to do it with "MultipleKeys" function by adding [{F5}] into"keyocodes" field. But, since it's only one key, i guess same could be done with "key" command... right or wrong? I didn't manage to make it work... 

----

**Comment by LAB02-Admin** [comment]
Hi @Protoncek, thank you ❤️ 

You are correct, you can use a Key command. The current version has bugs though and doesn't really work, but the new release (coming this weekend) will have a working version. It'll also detect your key, so you'll just have to press F5 when the input field is selected, and it'll enter the correct value for you.

Hope that helps!

**Comment by Protoncek** [comment]
ok, thanks a lot, that will be great ! looking forward to it!
