### ISSUE TITLE
Buttons missing

### ISSUE THREAD

**Issue by dino-prpic** [LAB02-Research/HASS.Agent#19]
I have trouble configuring new sensors and commands. The buttons shown in readme are not displayed, as you can see here:

![hass_agent_malfunction_sensors](https://user-images.githubusercontent.com/23002957/148573326-2970d2c8-0934-4537-8b22-d583271ba0b6.jpg)
![hass_agent_malfunction_cmd](https://user-images.githubusercontent.com/23002957/148573330-87e3c411-c64a-418f-8f75-1711802e9283.jpg)

**Comment by LAB02-Admin** [comment]
That's new. The form is resizable, can you try resizing a bit to see if the buttons pop up?

What resolution do you use, and what scaling?

**Comment by dino-prpic** [comment]
I had scaling set to 115%, that was the problem. When i set it to 100% the buttons appeared. 
Thanks!

**Comment by LAB02-Admin** [comment]
Alright, thanks for letting me know. I'll look into it, tested with 125% scaling but that went fine.
