### ISSUE TITLE
Bug: Installer wrongly failed internet connectivity test

### ISSUE THREAD

**Issue by waps11** [LAB02-Research/HASS.Agent#196]
**Describe the bug**
Installer keeps issuing a warning about a failed internet connectivity check and offers no choice to continue installation.  I do have stable internet connectivity but I have disallow connectivity checks at the local and network firewall level for privacy purpose so my network interface shows up as not internet connected while in reality being connected and usable for internet browsing. 

**Expected behavior**
The user should be offered the choice to ignore the warning and continue installation. On the other hand, the connectivity test could be refactor to truly test only needed remote endpoints and not blindly trust what the local network interface says.

**Misc info (please complete the following information):**
 - Windows 10 latest
 - HASS.Agent version: 2022.12 trying to upgrade to 2022.13 (the problem is not new to this release, in earlier releases I enabled my LTE hot spot to temporarily bypass the problem which is less than ideal...)

Please check what's applicable (multiple answers possible):

 - [x] Installed via installer
 - [ ] Installed manually
 - [ ] Problem occurs in HASS.Agent
 - [ ] Problem occurs in Satellite Service

**Comment by LAB02-Admin** [comment]
Interesting, thanks for reporting, I'll look into it

**Comment by LAB02-Admin** [comment]
Should be fixed in the latest beta if you want to test:
https://github.com/LAB02-Research/HASS.Agent/releases/tag/2022.14.0-beta1

**Comment by waps11** [comment]
> Should be fixed in the latest beta if you want to test: https://github.com/LAB02-Research/HASS.Agent/releases/tag/2022.14.0-beta1

Just tested the beta and everything went smoothly. Thanks!
