### ISSUE TITLE
Bug: alternative dpi results in wrong resolution, incomplete display naming

### ISSUE THREAD

**Issue by ITensEI** [LAB02-Research/HASS.Agent#199]
**Describe the bug**
Display sensors showing incorrect resolution. I have 3 monitors 1920x1080 and a 4k TV (3840x2160) attached to my PC. I'm using both the GPU and onboard graphics for one of the monitors. The sensors are showing 3 displays at 1920x1080 and 1 display at 1280x720. 

The names are all DISPLAY# so I'm not sure which one is which. I'm wondering what method is used to get the display info and if it's possible to get the display name

**Expected behavior**
Ideally show proper resolution per display
Having the display name show up in attributes would be helpful

**Screenshots**
![image](https://user-images.githubusercontent.com/9561099/197853583-128b5f62-67df-48c2-90ff-d36074f04c73.png)
![image](https://user-images.githubusercontent.com/9561099/197853671-e3be49dc-3782-4179-94dc-3fd92e9d7458.png)

**Misc info (please complete the following information):**
 - ![image](https://user-images.githubusercontent.com/9561099/197853880-100b0e4f-6e11-4d99-894d-42947ae5e726.png)
 - Windows' UI language: English
 - HASS.Agent version: 2022.13.0

Please check what's applicable (multiple answers possible):

 - [x] Installed via installer
 - [ ] Installed manually
 - [ ] Problem occurs in HASS.Agent
 - [ ] Problem occurs in Satellite Service

**Additional context**

**Comment by ITensEI** [comment]
I switched the display scale from 300% to 100% which now shows DISPLAY3 with the correct resolution. Curious why the scaling was making it think it was 720p as the content played on the TV still looked 4K with the scaling. So I suppose now this is more of a feature request for proper display names

**Comment by LAB02-Admin** [comment]
That's very interesting, I'll look into it, thanks

**Comment by LAB02-Admin** [comment]
Should be fixed in the latest beta if you want to test:
https://github.com/LAB02-Research/HASS.Agent/releases/tag/2022.14.0-beta1

**Comment by LAB02-Admin** [comment]
Fix in latest release: https://github.com/LAB02-Research/HASS.Agent/releases/tag/2022.14.0
