### ISSUE TITLE
Hotkeys for each action?

### ISSUE THREAD

**Issue by FiftyFour7250** [LAB02-Research/HASS.Agent#2]
Just a suggestion, I'm using another utility from github for this now, but it would be cool if it were in your app as well.

Now it's possible to open window with the launch of scripts and automation using hotkeys, . But it would be very cool if the application had the ability to set hotkeys for each automation and script that will immediately launch them.

**Comment by LAB02-Admin** [comment]
That's a great idea, will do, thanks :)

**Comment by LAB02-Admin** [comment]
This has been added in the [latest release](https://github.com/LAB02-Research/HASS.Agent/releases/tag/v2021.12.3). 

Thanks for the tip!
