### ISSUE TITLE
Bug: quickaction-bound hotkeys not working

### ISSUE THREAD

**Issue by b26x** [LAB02-Research/HASS.Agent#20]
Hey there! First of all I would like to say thanky soooo much! This little program is just a dream! :)
But unfortunately I'm unable to get the quick actions hotkeys working.
On the other hand the shortcut for opening the quick action gui is working fine.

Please respond to this issue if you need any additional information.

**Comment by b26x** [comment]
If tried different key combination aswell as different actions to be triggert - none of the tries were successful.

**Comment by LAB02-Admin** [comment]
Hi @b26x, thank you! That's very nice to hear :)

I've had that issue reported before, so I'd really like to tackle it. The easiest way to do that is if I can reproduce the problem locally. Could you please provide me with the following:

- Your Windows version and build (you can find out by pressing winkey + r, then enter 'winver')
- Your Windows- and keyboard language
- The hotkeys you used

I'm gone for the week so no hurry.

**Comment by LAB02-Admin** [comment]
And: do you use Microsoft Powertoys, specifically Powertoys Run and even more specifically with 'Use centralised keyboard hook' enabled?

**Comment by b26x** [comment]
I'm using a german keyboard layout (QWERTZ) aswell as using German as the system language on Windows 10 Version 21H1 (Build 19043.1466). The hotkeys I tried are the following:
- Ctrl + shift + P
- Ctrl + Ö
- Ctrl + alt + Ö
- Ctrl + alt + P
- Ctrl + alt + N

And yes I'm using Windows PowerToys Run, but the option 'Use centralised keyboard hook' is deactivated.
Feel free to ask for any additional information that might help :)

**Comment by LAB02-Admin** [comment]
Thanks for the info!

Well, when you have some spare time; could you try closing Powertoys and see if that helps? Maybe restart HASS.Agent afterwards, to make sure all keybindings get re-registered. And if that doesn't work, temporarily disable Powertoys start-on-boot, then reboot and see if it helps. Of course you can reenable Powertoys afterwards. 

It seems like their keyboard hook is blocking others - not sure yet though, might be coincidental.

**Comment by Syntoxr** [comment]
I'm too having this same issue. Not using Powertoys but Auto Hotkey (Disabling it didn't help).

- Build 19043.1466
- German QWERTZ Key layout
- Some random combinations I've tested
  - Ctrl + shift + L
  - Ctrl + Shift + T
  - Ctrl + G 

However, opening Quick actions via Ctrl + shift + Q works fine like b26x already said.
Happy to provide more info or test some stuff

**Comment by LAB02-Admin** [comment]
Hi @Syntoxr, thanks for taking the time to post :)

Interesting that you're also using a hotkey tool, and also a German keyboard. I'll prepare a German VM tonight to do some tests, but could you please test the following:

Disable AH, make sure it doesn't start on boot. Reboot your PC, and then try the shortcuts again.

**Comment by Syntoxr** [comment]
Already did that.
- Removed AHK script from Autostart folder
- Rebootet
- Searched with ProcessHacker for running AHK Scripts, services or anything other, but none were running.

**Comment by LAB02-Admin** [comment]
Very thorough, nice :) Alright, I'll focus testing on the language then

**Comment by Syntoxr** [comment]
Just had the idea to look at the logs...
This warn gets logged whenever I trigger a hotkey:
```
[WRN] [HOTKEY] Registered hotkey no longer bound to a QuickAction: Shift, Control + L
```
I quickly did some more testing and found out, that all hotkeys work, but only if there are more than one configured.

**Comment by b26x** [comment]
I can replicate it. Everything is working fine with more than one hotkey configured and Powertoys Run (as well as AH) running in the background.

**Comment by LAB02-Admin** [comment]
That's some great debugging! And a very nasty bug (wrote `==` instead of `!=`)..

I've published a beta release with a few fixes, including this one. Could you please test it?

https://github.com/LAB02-Research/HASS.Agent/releases/tag/b2022.1.18

**Comment by Syntoxr** [comment]
Just found that too. 
Update works like it should now.
Many thanks!

**Comment by LAB02-Admin** [comment]
Great, you're very welcome :) I'll close this ticket, if it's not resolved for you @b26x, please reopen!
