### ISSUE TITLE
Bug: tts not working with new integration

### ISSUE THREAD

**Issue by Growiel** [LAB02-Research/HASS.Agent#200]
**Describe the bug**
With the latest version and new integration, TTS is not working, the logs show the following error:

`2022-10-25 21:22:28.209 ERROR (MainThread) [custom_components.hass_agent.media_player] Invalid media type 'music'. Only music is supported!`

**To Reproduce**
1. Install HASS.Agent latest version
2. Enable media_player in config
3. Install HASS.Agent integration through HACS
4. Go to developer tools, try to send a TTS message:
![image](https://user-images.githubusercontent.com/5228735/197865360-97b0fb26-4743-4100-be6e-a13ebde014a6.png)

**Expected behavior**
TTS to be played

**Misc info (please complete the following information):**
 - Windows build (ideally screenshot/info of `winver.exe` output): 
 
![image](https://user-images.githubusercontent.com/5228735/197865425-9552ce58-ba54-4eca-91f6-02f33438e55a.png)

 - Windows' UI language: 
 en_US

 - HASS.Agent version: 2022.13.0

Please check what's applicable (multiple answers possible):

 - [x] Installed via installer
 - [ ] Installed manually
 - [x] Problem occurs in HASS.Agent
 - [ ] Problem occurs in Satellite Service

**Comment by LAB02-Admin** [comment]
Hi @Growiel,

You're absolutely right! This has been patched, an update for the integration should show up in HACS soon. Let me know if that fixes it for you.

**Comment by Growiel** [comment]
Confirmed it works!
