### ISSUE TITLE
Bug: Wrong characters with PowershellSensors

### ISSUE THREAD

**Issue by icegothic** [LAB02-Research/HASS.Agent#201]
Hi, 

I made a powershell script to get my CPU core's temperature. It returns something like "38.4°C" but when I execute it via HASS Agent's sensor configuration, the returned value looks like "38.4øC". Sadly that's also what appears on my HomeAssistant dashboard.

I tried on 2 computers even checked many other chars and many seems to have an issue... Is it an UTF8 issue?

![powershell_HomQCNXHC0](https://user-images.githubusercontent.com/16883752/198848256-06d7b106-ac09-4a3e-afc1-a412474a6073.png)

OS: WIndows 11
HASS Agent: 2022.13.0
OS display in english but input in french

**Comment by LAB02-Admin** [comment]
Could be, I'll look into it, thanks for reporting: [[hassagent-164](https://lab02research.youtrack.cloud/issue/hassagent-164)]

**Comment by LAB02-Admin** [comment]
Think I fixed this, is it possible to give me the powershell script so I can make sure?

**Comment by LAB02-Admin** [comment]
Should be fixed in the latest beta if you want to test:
https://github.com/LAB02-Research/HASS.Agent/releases/tag/2022.14.0-beta1

**Comment by LAB02-Admin** [comment]
Fixed in https://github.com/LAB02-Research/HASS.Agent/releases/tag/2022.14.0
