### ISSUE TITLE
Feature: mediaplayer and notificarions for all users

### ISSUE THREAD

**Issue by blair287** [LAB02-Research/HASS.Agent#202]
Please make sure your feature isn't already listed on HASS.Agent's issue tracker:

https://lab02research.youtrack.cloud/

There's a list of open bugs & features on the right. On the left you can see what's being worked on, what's planned and what's ready for the next release.

If you're not sure, don't worry, just go ahead and we'll discuss :)

----

**Is your feature request related to a problem? Please describe.**

As soon as I log off and anyone else logs in the media player and notifications stop working

**Describe the solution you'd like**

It be nice if you only have to install hassagent once and it works across multiple accounts

**Describe alternatives you've considered**

If you install for each account you'll end up with multiple notify and multiple media players so not very helpful for automations

**Additional context**

**Comment by LAB02-Admin** [comment]
You can if you install HASS.Agent in a directory that both users can access. Just make sure both users aren't logged in at the same time.
