### ISSUE TITLE
Enhancement: grouping point in port field

### ISSUE THREAD

**Issue by Syntoxr** [LAB02-Research/HASS.Agent#21]
This is just a very small thing. 
A grouping point gets displayed in port fields when onboarding and in the Notifications tab. It's just a cosmetic thing but may be a bit confusing, especially when talking about IP-addresses:
![image](https://user-images.githubusercontent.com/63484271/149579549-287fe4ad-08fe-46e3-98c7-a408f3d8d6fe.png)

**Comment by LAB02-Admin** [comment]
Agreed, will fix - thanks :)
