### ISSUE TITLE
Feature: also run on 32 bit windows

### ISSUE THREAD

**Issue by vb-git** [LAB02-Research/HASS.Agent#213]
I have an old Windows tablet laying around but it only runs Win10 32 bit. HASS.Agent won't run because it seems to require an 64 bit OS. I see no immediate need for 64 bit only (like >4GB memory) so maybe it can be compiled as 32 bit compatible?

**Comment by LAB02-Admin** [comment]
Hey @vb-git,

It's mostly for package compatability, but you can compile it as 32bit. @onexy did so in #188, specifically [here](https://github.com/LAB02-Research/HASS.Agent/issues/188#issuecomment-1287777056).

If you need help compiling, I can do it for you.

**Comment by vb-git** [comment]
Thanks, i had searched for it but did not find this. I will look into it to compile it myself!
