### ISSUE TITLE
Bug: 2022.14 update display resolution, display name gives 'unknown' state

### ISSUE THREAD

**Issue by deeguz** [LAB02-Research/HASS.Agent#218]
**Describe the bug**
Since 2022.14. update, the display resolution is not available in home assistant. It gives "unknown" state. Right after i updated to this version, and rebooted, it stopped working correctly.

**To Reproduce**
i started to use hass agent earlier, and then updated to 2022.14, and then the display resolution is unknown
**Expected behavior**
I hope somehow i can get it work

**Screenshots**
screenshot: https://drive.google.com/file/d/1CmMGnyKlYwunFcGmhC-LtIUUT8_14nyW/view?usp=share_link

**Misc info (please complete the following information):**
 - Windows build (ideally screenshot/info of `winver.exe` output): screenshot: https://drive.google.com/file/d/1xtWKQTDTvEKTvb0Eui2m3CrK0H7idXsX/view?usp=share_link
 - Windows' UI language: english
 - HASS.Agent version: 2022.14

Please check what's applicable (multiple answers possible):

 - [x] Installed via installer
 - [ ] Installed manually
 - [x] Problem occurs in HASS.Agent
 - [ ] Problem occurs in Satellite Service

**Additional context**

**Logs**
all the logs are compressed to zip and uploaded here: https://drive.google.com/file/d/1s0ROrKUY4_FcIcQa8NyDf1xmekNl4f12/view?usp=share_link

**Comment by LAB02-Admin** [comment]
Hi @deeguz,

There were a few small changes to the Display sensor. because combined with a non-default DPI the wrong values would show. However, I don't really recognize your screenshot - did you create that yourself with a template sensor?

You need to use any of these attributes:

![image](https://user-images.githubusercontent.com/81011038/203270271-8db9a95e-4b56-4ae2-b7c2-8e8ead89407c.png)

**Comment by deeguz** [comment]
Sorry, it was my fault. Before this update, the display resolution had its very own entity, now it's moved to display's attributes. I guess it's not a bug, so i guess it's solved :)
