### ISSUE TITLE
PC shuts off completely when activating Hibernate or Sleep

### ISSUE THREAD

**Issue by igalg99** [LAB02-Research/HASS.Agent#226]
I have an Desktop PC with windows 10 home version 22H2.
Hass.agent is configured correctly and services and commands are working. However, when I make a command to put PC to Sleep or Hibernate, it seems to shut down the PC completely which makes it impossible to Wake On Lan. 
When I go from windows start menu and put PC to sleep, it goes to sleep but not shuts down completely and then I can turn it on via Wake On Lan. So this function work. but I as said, when I try to put it to sleep or hibernate (tried both) , then it goes off completely.

anyone else has this problem? it would be nice to have the possiblity to put it to sleep and turn it on later remotely.

**Comment by eloyvl** [comment]
I have problems, when hibernate, after entering the session it turns off

**Comment by cableghost** [comment]
> I have problems, when hibernate, after entering the session it turns off
I'm wondering if this is the old issue of using command line for sleep if hibernation is enabled. As far as I could work w/, the only way I could ever make sleep work was to first turn off hibernation. Then, using another script, turn hibernation back on when logging in.

**Comment by loryanstrant** [comment]
I've got a couple of Surface devices (previously running IoTLink but now HASS.Agent) where I spent HOURS dealing with this.
In a nutshell, the standby states in Windows ignore logic or reason.
What I've had to do is disable EVERY standby/hibernate/sleep mode possible by using this as an example:
`
![image](https://user-images.githubusercontent.com/51473494/218254567-064c7770-380c-40bd-a2c8-b0cf9f01d4fb.png)
`
What this does is stops the device ever going to sleep, so then when you send commands to sleep or wake - it only turns the screen on or off.

**Comment by igalg99** [comment]
Thank you all for the replies. Unfortunately this thread became irrelevant and not possible for me to find and share a solution since the PC eventually dies and i received a full refund for it (probably had some other hardware issues that affected this specific issue with Hass.agent I opened). 
As for now with the new PC all works flawlessly as it should and intended.
