### ISSUE TITLE
Bug: dragging window can cause drawing issues

### ISSUE THREAD

**Issue by petarvucetin** [LAB02-Research/HASS.Agent#23]
When moving Agent window between monitors group lines are starting to duplicate.

![image](https://user-images.githubusercontent.com/179653/149817864-d584310d-6f9b-429e-b0df-1b933d361961.png)

Thank you for the awesome addon for HASS!

**Comment by LAB02-Admin** [comment]
Yep, nice catch, will fix. Thanks!

**Comment by LAB02-Admin** [comment]
Fixed in latest beta release: https://github.com/LAB02-Research/HASS.Agent/releases/tag/b2022.1.18

Thanks!
