### ISSUE TITLE
Misc: windows installer source ?!

### ISSUE THREAD

**Issue by mcarbonneaux** [LAB02-Research/HASS.Agent#232]
i'm interested how you have done the autodownload of the dotnet 6 in the installer... but i dont found the installer source !

**Comment by LAB02-Admin** [comment]
I use Advanced Installer for that :)

**Comment by mcarbonneaux** [comment]
ok i while go to see this one, seem to be more simple to use than wixx.. !
you can share the configuration file or not ?
