### ISSUE TITLE
Bug: Auto run registry entry missing quotes around path

### ISSUE THREAD

**Issue by nsleigh** [LAB02-Research/HASS.Agent#233]
**Describe the bug**
When I logon to my machine HASS.Agent isn't running, I discoved that the registry key HKCU\Software\Microsoft\Windows\CurrentVersion\Run entry doesn't have quotes around the path and as my user account include a space then the code doesn't run e.g. "C:\Users\My Name Here\AppData\Roaming\LAB02 Research\HASS.Agent\HASS.Agent.exe"

**To Reproduce**
Check register key HKCU\Software\Microsoft\Windows\CurrentVersion\Run value HASS.Agent and the value doesn't have quotes.

**Expected behavior**
HASS.Agent.exe runs on logon if you have a space in your logon name.

**Screenshots**
N/A

**Misc info (please complete the following information):**
 - Windows build (ideally screenshot/info of `winver.exe` output): Windows 11 but would be the same on other versions.
 - Windows' UI language: 
 - HASS.Agent version: 

Please check what's applicable (multiple answers possible):

 - [x] Installed via installer
 - [ ] Installed manually
 - [x] Problem occurs in HASS.Agent
 - [ ] Problem occurs in Satellite Service

**Comment by LAB02-Admin** [comment]
❤️
