### ISSUE TITLE
Bug: Retain flag not set for MQTT sensors

### ISSUE THREAD

**Issue by oNSXo** [LAB02-Research/HASS.Agent#239]
**Describe the bug**
Seems similar to #128.  On a reboot of HA Core, all of the PC sensors flip to unknown.  Last active will update as its value continues to change, even though the retain flag is set in the settings.

Using MQTT Explorer, the topics to not have any retained state.

**Expected behavior**
Upon restarting HA Core, the last known values should be retained and restored to their sensors upon start.

**Screenshots**
![image](https://user-images.githubusercontent.com/34994438/209442405-f2602f47-63c6-49a9-a6e9-1a1a2ee32b4f.png)

![image](https://user-images.githubusercontent.com/34994438/209442506-f6a69e66-7f9b-4a90-8116-4158b6ff8c88.png)

**Misc info (please complete the following information):**
 - Windows build (ideally screenshot/info of `winver.exe` output): 
 
![image](https://user-images.githubusercontent.com/34994438/209442486-04e2c276-a0a1-4557-84a5-e2d73ed4d094.png)

 - Windows' UI language:  English
 - HASS.Agent version:  2022.14.0

Please check what's applicable (multiple answers possible):

 - [x] Installed via installer
 - [ ] Installed manually
 - [x] Problem occurs in HASS.Agent
 - [ ] Problem occurs in Satellite Service

**Comment by JOHLC** [comment]
I am also seeing this every time I restart Home Assistant

**Comment by cableghost** [comment]
Yep, me as well, specifically using the Session State sensor.

**Comment by kressir** [comment]
It looks like the HASS.Agent.Shared package does not set the retain flag.  For a test, I set the retain flag true in Models.HomeAssistant.AbstractSingleValueSensor.PublishStateAsync by adding the .WithRetainFlag(true).  That gave me a retain flag on the state topics.
![image](https://user-images.githubusercontent.com/7967757/224417277-23fc9ec6-5f15-4b46-9c67-69856190a5d2.png)

**Comment by cableghost** [comment]
The Retained Flag still doesn't seem to be working. Although I have it enabled, I'm still getting Unknown for SessionState if I restart HA during an unlocked Windows session.
