### ISSUE TITLE
Bug: Microphone process & Webcam process sensors only return one process

### ISSUE THREAD

**Issue by jordandrako** [LAB02-Research/HASS.Agent#249]
Please make sure your bug isn't already listed on HASS.Agent's issue tracker: There is, but look at the additional context for why I'm making this issue.

----

**Describe the bug**
The sensor only reports one process, but multiple processes can access the mic at once.

**To Reproduce**
While using a mixer software, such as Voicemeeter or Steelseries Sonar, start a voice call using Teams or Zoom or similar.

**Expected behavior**
A list of all the processes should be returned as a state attribute to avoid state character limit in cases there are a lot of processes active.

**Screenshots**
![image](https://user-images.githubusercontent.com/7110658/211641988-a7021422-0477-4e56-90ae-6b4a082b9c10.png)

**Misc info (please complete the following information):**
 - Windows build (ideally screenshot/info of `winver.exe` output):  22623.746
 - Windows' UI language: English
 - HASS.Agent version: 2022.14.0

Please check what's applicable (multiple answers possible):

 - [x] Installed via installer
 - [ ] Installed manually
 - [x] Problem occurs in HASS.Agent
 - [ ] Problem occurs in Satellite Service

**Additional context**
I know there's already a ticket for this in YouTrack, but I wrote the process sensor for hass-workstation-service. That project is now deprecated and somebody reported a bug with it that I have made a PR to address. Please feel free to use the code I wrote in that branch to adjust this sensor. https://github.com/sleevezipper/hass-workstation-service/pull/197/files

**Logs**
If possible, please provide the logs of HASS.Agent and - if applicable - the Satellite Service. You can find HASS.Agent's logs by going to the main window, then `Configuration` -> `Logging` -> `open logs folder`. The Satellite Service's logs are in the same window, but the `Satellite Service` tab -> `open service logs folder`. If you want, you can mail them to lab02research@outlook.com

**Comment by HeedfulCrayon** [comment]
I just ran into this same issue occuring on my set up as well. I don't have the logs, but I can easily reproduce the issue.  I will enable the extended logging and mail it later

**Comment by eugeneniemand** [comment]
Agreed with OP I have 3 processes accessing my microphone when I'm on a call as I use an external mic and mixing console etc
![image](https://user-images.githubusercontent.com/6813309/212292950-54c11a2d-905d-49bd-92df-67dd7af11d34.png)

**Comment by jordandrako** [comment]
I've made a pull request to solve this issue. https://github.com/LAB02-Research/HASS.Agent.Staging/pull/5

**Comment by LAB02-Admin** [comment]
Thanks @jordandrako! ❤️
