### ISSUE TITLE
Enhancement: prefix switches and sensors with definable device name

### ISSUE THREAD

**Issue by Avishadur** [LAB02-Research/HASS.Agent#25]
Not a huge thing; but when you define your sensors and commands, the default that it uses just shows up in hass as "switch.shutdown", "sensor.cpuload", et cetera.
Currently I can obviously manually rename them to show up as <PC name>_shutdown; but I still have a bunch of MQTT sensors where it isn't clear which device they're from but I am pretty sure it's a windows machine's network cards.

This stands out more if you have multiple PC's and windows devices in the home

**Comment by LAB02-Admin** [comment]
Hi @Avishadur, you're absolutely right, it's a mess currently. I'll be releasing a new version this weekend which addresses this issue.

On one hand, the prefilled name for all sensors will now be `{machinename}_{sensortype}` and `{machinename_{commandtype}` for commands.. Second, all sensors created by the multivalue sensors will now be `{parent_multivaluesensor_name}_{sensor_descriptive_name}`.

You can just change the prefilled name, but by making it a bit custom it should make them easier to discern even when keeping the defaults.

**Comment by LAB02-Admin** [comment]
You can find the sensor's origin by going to HA, press `c`, search for and go to **Devices**. Then look up the name of your PC. In there, you'll see which entities belong to it.

If you want a clean slate before the new version, delete the multivalue sensors from HASS.Agent, store, and then completely close HASS.Agent. Afterwards, delete the machine that was created by HASS.Agent by clicking `DELETE` in the device info pane.

Afterwards restart HASS.Agent, and all remaining commands/sensors will get recreated with the same id's, so all your automations etc will still work.

When the new version's released, recreate the multivalue sensors and you'll have them with the right naming scheme.

**Comment by LAB02-Admin** [comment]
Fixed in v2022.1.23
