### ISSUE TITLE
Feature: quick action support for covers

### ISSUE THREAD

**Issue by ipd-otto** [LAB02-Research/HASS.Agent#28]
I just noticed that the quick actions do not support covers yet. I am already getting used to this feature for lights, so this would be a nice addition.

**Comment by LAB02-Admin** [comment]
Will do :)

**Comment by LAB02-Admin** [comment]
Hi @ipd-otto, I've added support in [the latest beta](https://github.com/LAB02-Research/HASS.Agent/releases/tag/b2022.2.13). I don't have any covers, could you please test it?

**Comment by LAB02-Admin** [comment]
Sorry, that release was incomplete, please use this one:

https://github.com/LAB02-Research/HASS.Agent/releases/tag/b2022.2.14

**Comment by ipd-otto** [comment]
Just got some time to test: I've added a quick-action toggle for my cover and it's working just fine. If I encounter any issues, I'll get back to you.
