### ISSUE TITLE
Bug: "failed to connect" triggers too fast after waking up

### ISSUE THREAD

**Issue by amplitur** [LAB02-Research/HASS.Agent#29]
Shortly after my PCs/laptops are waking up from sleep the HASS.Agent complains once about not being able to connect to the MQTT broker faster than Windows is reconnecting to the network again:

![image](https://user-images.githubusercontent.com/28072694/151686378-d888de80-7faa-40fb-a26c-393c4e9bb413.png)

This always happens when waking up, on multiple different devices.

Perhaps allow for some more retries (always or just during x secons window after waking up) before raising the "failed to connect" error?

**Comment by LAB02-Admin** [comment]
Good call! Will do, I'll add a network-up check as well. Thanks :)

**Comment by LAB02-Admin** [comment]
Fixed in [latest beta](https://github.com/LAB02-Research/HASS.Agent/releases/tag/b2022.2.13). You can optionally change the grace period in the config window.
