### ISSUE TITLE
Feature: Publish as a media_player (device class speaker)

### ISSUE THREAD

**Issue by DeftNerd** [LAB02-Research/HASS.Agent#31]
I find myself using the TTS HASS feature (a nice [one is available if you use the premium cloud service](https://www.nabucasa.com/config/tts/)) to have text, often notifications, turned into audio that's sent to media players. 

It would be stellar if the HASS.Agent could publish itself as a media player (in the ["speaker" device class](https://www.home-assistant.io/integrations/media_player/#device-class)) so Home Assistant could send audio streams to the agent for playback using the Windows audio subsystem, as well as do a few other things available to ["speaker" devices](https://www.home-assistant.io/integrations/media_player/#media-control-services) such as unmuting and controlling the volume.

This might be better suited for the HASS.Agent-Notifier repository as it would likely be used more as a notification option, but I could also see people wanting to use it to play music or something. Perhaps this could be spun off as another additional service like HASS.Agent-MediaPlayer

Similar ways to accomplish this:

- A similar project is at https://github.com/pcwii/HApyAudio but it has VLC as a requirement. 
- One can add the [VLC telnet integration](https://www.home-assistant.io/integrations/vlc_telnet/) in HomeAssistant to communicate with VLC directly using telnet. Presumably, [VLC has to be set up as a windows service](https://wiki.videolan.org/Windows_service/). 
- Another integration is [VLC without telnet](https://www.home-assistant.io/integrations/vlc/) (HTTP?). Not sure if this is better or worse than the telnet method. 
- One can set up [Music Player Daemon](https://www.home-assistant.io/integrations/mpd/). Haven't tried this yet, but it seems [more oriented towards linux](https://mpd.readthedocs.io/en/stable/user.html#compiling-for-windows) and doesn't integrate into windows that well. 
- Can have [Clementine Media Player](https://www.home-assistant.io/integrations/clementine/) running on the computers. While I know it can be minimized to the system tray on close, I don't think it can be set to start without the GUI and just in the system tray. 
- [AirServer](https://www.airserver.com/PC) acts as a GoogleCast/Aircast/Miracast receiver on any windows computer, but it costs money and isn't FOSS. 
- Very promising, [a .NET SnapCast Client](https://github.com/stijnvdb88/Snap.Net) application that's meant to run on startup. 

Something that uses native Windows features would be preferred and would be one less thing to install.

**Comment by LAB02-Admin** [comment]
Hi @DeftNerd, thanks for the (extensive) feature request. That does sound like a good idea, I currently use a pi for this purpose but one less device would be better.

Think it can be achieved with HA's websocket api. I'll put it on the list :)

**Comment by Growiel** [comment]
Hello,

Just a quick post to say that I think this is the only missing feature and am glad you are taking on the request. I like text notifications but sometimes I'm focused on something else and miss them. Having them play as TTS as well would be neat.

**Comment by LAB02-Admin** [comment]
This has been added to the latest beta:

https://github.com/LAB02-Research/HASS.Agent/releases/tag/2022.12.0-beta1
