### ISSUE TITLE
Powershell command issue

### ISSUE THREAD

**Issue by abel2660** [LAB02-Research/HASS.Agent#32]
Hey,
I am trying to run a python program with home assistant using the power shell command option. I don't know why it does not work. The command I type in is      C:/Users/....../AppData/Local/Programs/Python/Python39/python.exe "c:/Users/....../OneDrive/Documents/Python - Sk/PythonKeyPress/1.py". Do you have any solution for why it doesn't work?

**Comment by LAB02-Admin** [comment]
Hi @abel2660, the powershell command is to run powershell scripts, so this indeed won't work.

You can try using a CustomCommand. If there are spaces in the python executable path, you'll have to put that in quotes as well.

**Comment by abel2660** [comment]
Thanks for your answer, it works now 😀.
