### ISSUE TITLE
Bug: Actionable Notification with URL 

### ISSUE THREAD

**Issue by BNWEIN** [LAB02-Research/HASS.Agent#322]
----

**Describe the bug**
Using actionable notifications, and i am trying to make the action open a URL on my computer. 

**To Reproduce**
![image](https://github.com/LAB02-Research/HASS.Agent/assets/28929905/5c2af4f0-2530-4f0a-9927-4c1b33aece09)

**Expected behavior**
Click the "Open URL" button, and my browser to open and take me to the URL

**Screenshots**
![image](https://github.com/LAB02-Research/HASS.Agent/assets/28929905/59819e8e-b440-4f6a-a039-283a749c7b01)
Clicking "Open URL" does nothing

**Misc info (please complete the following information):**
![image](https://github.com/LAB02-Research/HASS.Agent/assets/28929905/70c44168-638b-4fa7-9ba4-3eb07723e7fb)
Hass.Agent Version 2022.14.0

Please check what's applicable (multiple answers possible):

 - [x] Installed via installer
 - [x] Problem occurs in HASS.Agent

**Logs**
Dont think you will need the logs?

**Comment by amadeo-alex** [comment]
Hello,

This is not a bug, such functionality is not supported at the moment. The only way to do this would be to use the "actionable notification" as described here https://hassagent.readthedocs.io/en/latest/notifications/new/notification-actionable/ , retrieving the button action click event in Home Assistant and then activating the "LaunchURL" which needs to be exposed from HASS.Agent:
![obraz](https://github.com/LAB02-Research/HASS.Agent/assets/68441479/d8e7f036-c445-4ac3-842d-c134df0d2028)

**Comment by BNWEIN** [comment]
Thanks. Someone in the discord helped me get exactly this setup and it’s working perfectly. Thank you

**Comment by BNWEIN** [comment]
And yep MrGeek right here :)
