### ISSUE TITLE
Feature: MQTT topic personalization 

### ISSUE THREAD

**Issue by matteo-martinelli** [LAB02-Research/HASS.Agent#326]
I would like to have the ability to personalize the topic where the information about my represented Windows PC are published, in order to organize my MQTT server topics structure as I want.

I would like to have a solution similar to the one present to point to the HomeAssistant discovery prefix.

**Comment by amadeo-alex** [comment]
Hello,
Please edit the title and issue to use the "Feature request" template.

**Comment by matteo-martinelli** [comment]
Done, I close this one.
