### ISSUE TITLE
Bug: missing culture causes integertextbox crash

### ISSUE THREAD

**Issue by Growiel** [LAB02-Research/HASS.Agent#33]
Hello,

Got the following error on step 3 of the onboarding on a new machine:

![image](https://user-images.githubusercontent.com/5228735/154372685-ccb8994e-4577-4779-ab66-d82359e00d4c.png)

Really didn't do anything special.

Thanks !

**Comment by Growiel** [comment]
A different, but similar, issue happens if I chose exit and then try to open the config from the main page:

![image](https://user-images.githubusercontent.com/5228735/154372935-c636c00b-d239-47a2-a3d4-12870819e93e.png)

**Comment by LAB02-Admin** [comment]
That is weird! And I can't reproduce it. 

Could you try the latest beta: https://github.com/LAB02-Research/HASS.Agent/releases/tag/b2022.2.17

If that doesn't work, what language is your OS?

**Comment by Growiel** [comment]
I'll try the beta at home tonight, but I can already answer the question, my OS is in English (US). I do have other languages (french, japanese and korean) installed.

Also while my language is English US, my region and formats (time, numbers, ...) are all set to France. Weird, I know.
I'm French but mainly use English in my everyday life but I refuse to use their weird mm/dd/yyyy format :D

**Comment by LAB02-Admin** [comment]
Pretty much the same setup here: EN instead of native, and without the weird date format - 100% agreed on that :p 

I reproduced your config in a VM, but was unable to reproduce the bug. However, I made a test version that could help. So if the beta fails, could you please overwrite HASS.Agent.exe with this one:

https://shares.lab02-research.org/tests/33/hass.agent.zip

Thanks :)

**Comment by Growiel** [comment]
Tried the new .exe, cannot start HASS.Agent at all anymore, even after rebooting. Should I wait for the new beta ?

**Comment by LAB02-Admin** [comment]
Could you please install this beta:

https://github.com/LAB02-Research/HASS.Agent/releases/tag/b2022.2.17

And then copy the [test exe](https://shares.lab02-research.org/tests/33/hass.agent.zip) into the installation directory, overwriting the existing one. Usually the directory is `%appdata%\LAB02 Research\HASS.Agent`.

Delete the `config` folder so you'll get the onboarding again. If it doesn't work, please check if there's anything in the `logs` subfolder and post it here.

**Comment by Growiel** [comment]
Sadly, it's not better.

And the logs aren't helpful sadly:

```
2022-02-17 22:41:36.515 +01:00 [INF] [LOG] Coderr exception reporting disabled
2022-02-17 22:41:36.516 +01:00 [INF] [PROGRAM] Extended logging disabled
2022-02-17 22:41:36.650 +01:00 [INF] [SETTINGS] Config storage path: C:\Users\Growiel\AppData\Roaming\LAB02 Research\HASS.Agent\config
2022-02-17 22:41:36.652 +01:00 [INF] [SETTINGS] No config found, storing default settings
```

It's a brand new install, I do have installed .net maybe i'm missing something else ?

**Comment by LAB02-Admin** [comment]
Alright, too bad. Let's enable extended logging. Could you please download this reg key:

https://shares.lab02-research.org/tests/33/hassagent_enable_extended_logging.zip

And doubleclick the .reg key to import. Afterwards, start HASS.Agent again and see if more info shows in the logs.

**Comment by LAB02-Admin** [comment]
Longshot, but you could please download this zip, and again place the .exe in your HASS.Agent install folder (overwriting the current one):

https://shares.lab02-research.org/tests/33/hass.agent.zip

Then rename your config folder before launching, so you'll get the onboarding again.

If that doesn't work, and extended logging isn't giving additional info, I'll remove the control that's causing this and build it myself.

Thanks for helping :)

**Comment by Growiel** [comment]
Hi

Sorry i wasn't home for a few days, i'll try it this evening (europe time) and let you know ! I appreciate your efforts in this.

**Comment by Growiel** [comment]
The new .exe sadly doesn't help. Here are the extended logs though
[[2022-02-22] HASS.Agent_20220222.log](https://github.com/LAB02-Research/HASS.Agent/files/8119752/2022-02-22.HASS.Agent_20220222.log)
!

**Comment by Growiel** [comment]
I checked the log and using the error message, I went to everyone's favorite website: Stackoverflow.

Here's what I got: https://stackoverflow.com/questions/42554944/how-to-solve-this-exception-culture-is-not-supported

The first answer is the correct one. I had my region set as English (Europe) but my Keyboard set as English (US).

I switch my region back to English US and manually overrode all the time formats to not be totally stupid.

I know my case is fairly rare so if you don't want to waste time fixing, no problem for me, it now works.

**Comment by LAB02-Admin** [comment]
Oh wow! Thanks for the extensive info, really helpful :) 

I'm able to reproduce it now. It's the `English (Europe)` part that's messing things up, and looks like it's a .NET flaw which I can't circumvent without rebuilding the integer-textbox myself. 

That wouldn't be too much of a problem, but I'm moving HASS.Agent to the newer .NET 6 in the coming months. So for now I'll leave it like this, and I'll add it to the documentation incase someone comes across it as well.
