### ISSUE TITLE
Bug: Typing of '@' character is not possible on whole system when agent is running

### ISSUE THREAD

**Issue by t46g** [LAB02-Research/HASS.Agent#340]
**Describe the bug**
When HASS.Agent is running on my Windows 10 machine, I am no longer able to type '@' chars. I am using a german keyboard, and the Agent is somehow blocking the typing. On a german keyboard the shortcut for '@' is 'Alt Gr + Q'. For example typing of a '€' is pretty similar: 'Alt Gr + E' and is working fine. When I quit the Agent by clicking on the tray icon, it will immediately work again. I have no quickactions configured, I only have a single dummy sensor.

**To Reproduce**
1. Boot machine with Agent on autostart.
2. Wait when Agent is started
3. Try to type '@' char -> not working

**Expected behavior**
When no shortcuts are configured, it should not affect typing of any characters on a keyboard.

**Screenshots**

**Misc info (please complete the following information):**
 - Windows build (ideally screenshot/info of `winver.exe` output): 22H2 19045.3208
 - Windows' UI language: German
 - HASS.Agent version: 2022.14.0

Please check what's applicable (multiple answers possible):

 - [x] Installed via installer
 - [ ] Installed manually
 - [x] Problem occurs in HASS.Agent
 - [ ] Problem occurs in Satellite Service

**Comment by amadeo-alex** [comment]
Possible duplicate of https://github.com/LAB02-Research/HASS.Agent/issues/292 & https://github.com/LAB02-Research/HASS.Agent/issues/225 & https://github.com/LAB02-Research/HASS.Agent/issues/122

Could you please try and configure different HotKey as https://github.com/LAB02-Research/HASS.Agent/issues/225#issuecomment-1387646483 suggested?

At some point this will be probably addressed by having a warning notification for German keyboard layouts.

**Comment by t46g** [comment]
Thank you very much, that solved my problem.

**Comment by Zarox666** [comment]
argl.... I was wondering for months whats wrong with my Gaming Keyboard or its driver that off all things the @ sign is not working sometimes....
then I look around in search of something different and find this thread.... yeah well, that explains it and also why @ works in the RDP connection to my laptop, but not on my PC, which my brain stored as "sometimes its working".

Thanks! 
one problem less.
