### ISSUE TITLE
Discovered entities with a name that starts with the device name

### ISSUE THREAD

**Issue by nerlins** [LAB02-Research/HASS.Agent#345]
I just installed your app on my Win10 LTSB server. This is popping up in Home Assistant:

> Some MQTT entities have an entity name that starts with the device name. This is not expected. To avoid a duplicate name the device name prefix is stripped off the entity name as a work-a-round. Please inform the maintainer of the software application that supplies the affected entities to fix this issue.
> 
> List of affected entities:
> 
> sensor.camserver_windowsupdates_available_driver_updates
> sensor.camserver_gpuload
> sensor.camserver_cpuload
> sensor.camserver_storage_c
> sensor.camserver_currentclockspeed
> sensor.camserver_memoryusage
> sensor.camserver_storage_d
> sensor.camserver_windowsupdates_available_software_updates
> sensor.camserver_storage_total_disk_count
> sensor.camserver_windowsupdates_software_updates_pending
> sensor.camserver_windowsupdates_driver_updates_pending
> sensor.camserver_lastboot
> sensor.camserver_gputemperature

**Comment by TarheelGrad1998** [comment]
I just got the same when updating to 2023.8.  It's something in the new MQTT rules.  I manually changed the names in the HA entities, is that enough of a workaround for now?  Not sure...

**Comment by IeuanK** [comment]
> I just got the same when updating to 2023.8. It's something in the new MQTT rules. I manually changed the names in the HA entities, is that enough of a workaround for now? Not sure...

Manually fixing it is a workaround for sure, but Home Assistant explicitly states to let the maintainers know so that they can fix it. Especially something such as HASS.Agent which has lots of sensors you shouldn't have to do this manually.

**Comment by nogweii** [comment]
This is a duplicate of #337 .

**Comment by nerlins** [comment]
> This is a duplicate of #337 .

So, do you want me to rename everything by hand, or wait for a proper code update?

**Comment by hastarin** [comment]
> > This is a duplicate of #337 .
> 
> So, do you want me to rename everything by hand, or wait for a proper code update?

I would suggest you close this ticket and vote up #337 so the one ticket has the focus.

**Comment by TarheelGrad1998** [comment]
> > I just got the same when updating to 2023.8. It's something in the new MQTT rules. I manually changed the names in the HA entities, is that enough of a workaround for now? Not sure...
> 
> Manually fixing it is a workaround for sure, but Home Assistant explicitly states to let the maintainers know so that they can fix it. Especially something such as HASS.Agent which has lots of sensors you shouldn't have to do this manually.

Unless I did something wrong, it did not fix it at all.  I still got the warning when I rebooted again.  That is, after I changed the device name in the HA entity AND changed the names of every entity (so the prefix was totally different).

**Comment by amadeo-alex** [comment]
@nerlins Please close this as it's a duplicate of https://github.com/LAB02-Research/HASS.Agent/issues/337
Please always check if the issue you're facing already exists and use the issue template.

**Comment by nerlins** [comment]
K. Thought the maintainer had the ability to close a ticket. I haven't had time to log back in.
