### ISSUE TITLE
Allow MQTT clientId to be set in config

### ISSUE THREAD

**Issue by Zolli** [LAB02-Research/HASS.Agent#35]
Hy,

I use VerneMQ as my mqtt broker and this broker (and alos the MQTT 5 specs as i understand) require every client to have a static and unique cleintId for authentication. As i reviewed the code i found out that the code generates a random Id every connection attemp. Colud you make this possible to configure it in the UI, and if its not set generate a random one?

**Comment by LAB02-Admin** [comment]
Sure no problem, will do

**Comment by LAB02-Admin** [comment]
Released a new beta which implements this: https://github.com/LAB02-Research/HASS.Agent/releases/tag/b2022.2.28

I've also changed the behavior in that it generates a random one, then stores that ID so it'll stay consistent instead of changing every session.

Hopefully it's fixed for you now!

**Comment by Zolli** [comment]
Nice implementation, tested both ways and it works as expected. Thanks for the quick reaction.
