### ISSUE TITLE
It's broken, and marked as a virus(

### ISSUE THREAD

**Issue by FiftyFour7250** [LAB02-Research/HASS.Agent#4]
Hey, thanks for adding keyboard shortcuts, but I haven't been able to test them yet. Already when downloading, my browser detected a threat in the archive, so I downloaded the new version through another browser, but when unpacking Windows Defender detected a Trojan:Win32/Sabsik.TE.A!ml in HASS.Agent.exe so I uploaded both the archive and only one the exe file on Virustotal, and nothing was found there. So I decided to add this to the exception, but the app just won't start. Windows Defender doesn't have any complaints at all anymore, but even after restarting PC, when I try to launch the app, nothing happens :c

**Comment by LAB02-Admin** [comment]
Hey @FiftyFour7250, thanks again, you've been really helpful with your posts :)

I've signed all the binaries with an EV-code signing certificate. Could you download the updated .zip to see if it's accepted?

**Comment by FiftyFour7250** [comment]
Looks like it's no longer detected as a virus, but still doesn't start(

**Comment by LAB02-Admin** [comment]
Should work now: [HASS.Agent.zip](https://github.com/LAB02-Research/HASS.Agent/releases/download/v2021.12.3/HASS.Agent.zip)

**Comment by FiftyFour7250** [comment]
Yea, perfect. Thanks)
