### ISSUE TITLE
Feature: sync sensor state with HA api's current value

### ISSUE THREAD

**Issue by cromelex** [LAB02-Research/HASS.Agent#41]
When I wake up my laptop from Sleep, the SessionState sensor goes from Unavailable to Locked, but doesn't seem to then update to Unlocked.

I can manually force it to update by locking the screen and unlocking again.

As it is mentioned in the credits for this project,I will go and mention that the exact same issue happens for the HassWorkstation Service app ( https://github.com/sleevezipper/hass-workstation-service/issues/172 ), so I am wondering if similar or same code was used in this situation.

Edit: I linked to the wrong issue in HASS Workstation

**Comment by LAB02-Admin** [comment]
Hi @cromelex,

Thanks for reporting this. HASS.Agent uses different code for retrieving the session state than hass-workstation-service. The issue you linked regards the session changing id, and that doesn't seem to be the case here.

I'll look into it!

**Comment by cromelex** [comment]
Noted. I will try to replicate the issue again with screenshots to better document what is happening and reply back.

**Comment by cromelex** [comment]
Okay, some feedback.

As my laptop is docked (via USB-C for display and wired network), it looks like it is taking 30-60s for the network connection to be fully established, not sure if this is impacting the timing of the sensor update:
I have my SessionState sensor set to update every 10s which was the default.

1. Computer is put to sleep/lid closed -> status changes to Unavailable, as expected
2. Computer lid is opened and Windows login is done via Windows Hello within a couple of seconds -> sensor status takes up to 30/60s to update, and then updates to Locked. 
<img width="274" alt="session state locked" src="https://user-images.githubusercontent.com/96779452/159177845-efe8db50-61ba-432d-8b3f-e5e5f20e9fbe.PNG">

3.  If I lock and unlock my Session, state updates to Unlocked as expected.
<img width="286" alt="session state unlock after" src="https://user-images.githubusercontent.com/96779452/159177858-8953eb55-d141-4e64-8803-fb0f0ca8339f.PNG">

I was able to reproduce the issue multiple times.

I did a second process where the issue did not show up:
1. Computer is put to sleep/lid closed -> status changes to Unavailable, as expected
2. Computer lid is opened, I wait 30/60s with the screen locked until the sensor status changes to Locked (as checked from a 3rd device).
3.  Computer is unlocked -> Status changes to Unlocked within 10s, as expected.


So the issue actually seems to relate to the timing of the Locked->Unlocked status change,

Hope this helps.
Thanks

**Comment by LAB02-Admin** [comment]
That really helps a lot, and actually gave me an idea to make all sensors more reliable. I'll write it out here so I won't forget:

Currently sensors only send their value, when the value has changed compared to last round. This takes away some pressure from the mqtt broker. However, in this case, hass.agent thinks it sent the value while in fact HA hasn't received it. 

I have implemented a feature which forces all sensors to resend their value after a disconnection, but apparently that doesn't get properly registered in this case.

So, the idea: I'll use the HA API to fetch the current state of the sensor, in other words, what HA thinks the current value is. If that value differs from the actual value, force resend the value.

This way, the values should always stay in sync between HA and hass.agent.

**Comment by cromelex** [comment]
Can i just double check that you made something to fix this on the latest release?
Just checked my Home Assistant logs and it looks like the issue hasn't happened in 3 days, which I think matches when I did the update to the latest release.
Thanks

**Comment by LAB02-Admin** [comment]
Hey @cromelex, you're on the stable release channel, so v2022.3.27? 

A lot changed there yea, almost the entire code base - but I didn't fix this bug on purpose. So if it's fixed, that's a happy coincidence :p

**Comment by cromelex** [comment]
Yes, I can confirm I'm on stable release, v2022.3.27. 

Running the sensor as local (not using the sattelite service for now, as only 1 user on my laptop).
I had a closer look at the logs and it really seems to be fixed, even if it was a happy coincidence.

As far as I am concerned you can close this bug as resolved (even if by coincidence).

Thanks

**Comment by LAB02-Admin** [comment]
Great, thanks for being so observant! 

I've changed to title to remind me of the sync-sensor-state idea, which I'll still implement to be 100% sure of correctly reported sensorstates.

**Comment by LAB02-Admin** [comment]
I'm closing most feature requests from github's issue list. They're not ignored, just moved to the [HASS.Agent Issue Tracker](https://lab02research.youtrack.cloud/) (you can find your link in a comment above). 

That tracker allows me to organise better through what's pending, being done, being released, etc. - instead of one long list, which is beginning to stress me out :p

I will however post a reply here when I've implemented your request, and feel free to still post here when you have any questions/additions.
