### ISSUE TITLE
Translation: Brazilian Portuguese.

### ISSUE THREAD

**Issue by LeandroIssa** [LAB02-Research/HASS.Agent#43]
Hello, I would like to translate HASS.Agent into Brazilian Portuguese, do you have any projects in lokalise or in POEditor?
If you have a project, what is the link to it? Thanks.

**Comment by LAB02-Admin** [comment]
That's really kind of you @LeandroIssa! I'll post back here when I have it ready :)

**Comment by LeandroIssa** [comment]
> Vou postar aqui quando estiver pronto :)‎

**Comment by LAB02-Admin** [comment]
Hey @LeandroIssa, I have POEditor set up. You can start translating here:

https://poeditor.com/join/project/R7HIVG0wie

Good luck, and thanks! Let me know if I can be of any assistance :)

**Comment by LeandroIssa** [comment]
> Hey @LeandroIssa, I have POEditor set up. You can start translating here:
> 
> https://poeditor.com/join/project/R7HIVG0wie
> 
> Good luck, and thanks! Let me know if I can be of any assistance :)

Thank you very much! HASS.Agent in Brazilian Portuguese will encourage many Brazilians who do not understand English to use the program! Thank you so!

**Comment by LeandroIssa** [comment]
@LAB02-Admin Translation of HASS.Agent into Brazilian Portuguese is complete!

![Captura de tela 2022-04-01 215853](https://user-images.githubusercontent.com/67451572/161357982-838ce051-ddaf-4ac7-9945-32a693fcd552.png)

**Comment by LAB02-Admin** [comment]
Wow, already! I'm impressed. And it's such a beautiful language, I'm really happy with this :) 

I'll go make a beta with the new translatation, so you can see how it looks.

I was thinking, maybe I could put a link on top of the github readme so Brazilian readers can easily find the download. I've used Google Translate, can you please tell me if it's ok:

>Clique aqui para baixar o instalador mais recente.

The installer now also has Brazilian Portuguese enabled (the program came with the translation built-in so that part was easy..).

Another thing I thought; the wiki has a lot of examples and info, but is currently all English. I could put a line on top of every page, with a link that automatically translates the page by Google Translate. That way, you don't have to do so manually, and users can still get info from it:

>Clique aqui para traduzir esta página para o português.

The only downside is, is that it only has 'Portuguese'. Do you think that's still useful? I've been reading up on some of the differences, and it looks like it'll still be understandable?

Let me know what you think :)

**Comment by LeandroIssa** [comment]
> 



> Wow, already! I'm impressed. And it's such a beautiful language, I'm really happy with this :)

Thank you very much! <3

> I'll go make a beta with the new translatation, so you can see how it looks.

I'm really excited about the beta version!

> I was thinking, maybe I could put a link on top of the github readme so Brazilian readers can easily find the download. I've used Google Translate, can you please tell me if it's ok:
> 
> > Clique aqui para baixar o instalador mais recente.

Perfect, the translation was great!

> The installer now also has Brazilian Portuguese enabled (the program came with the translation built-in so that part was easy..).
> 
> Another thing I thought; the wiki has a lot of examples and info, but is currently all English. I could put a line on top of every page, with a link that automatically translates the page by Google Translate. That way, you don't have to do so manually, and users can still get info from it:
> 
> > Clique aqui para traduzir esta página para o português.
> 
> The only downside is, is that it only has 'Portuguese'. Do you think that's still useful? I've been reading up on some of the differences, and it looks like it'll still be understandable?
> 
> Let me know what you think :)
> 
> Edit: I just realised that most users probably have 'translate English into Portuguese' enabled by default in their browser, so maybe it's pointless. Either way is fine by me, as long as they feel welcome and included.

Yes, usually people have the automatic translation option enabled!
About README, just having written that you have the translation of HASS.Agent into Brazilian Portuguese will help a lot!


A ReadMe sentence like: "HASS.Agent is now in Brazilian Portuguese for Brazilians and Portuguese-speaking users!"
And below the phrase you had translated!

"Agora o HASS.Agent está em português do Brasil para brasileiros e usuários de língua portuguesa!
Clique aqui para baixar o instalador mais recente com a tradução!"

**Comment by LAB02-Admin** [comment]
Hey @LeandroIssa,

Been busy tweaking the interface to make everything fit nicely, it's looking great 😄 

> A ReadMe sentence like: "HASS.Agent is now in Brazilian Portuguese for Brazilians and Portuguese-speaking users!"
> And below the phrase you had translated!
>
> "Agora o HASS.Agent está em português do Brasil para brasileiros e usuários de língua portuguesa!
> Clique aqui para baixar o instalador mais recente com a tradução!"

That is perfect! 


There are a few strings that I'd forgotten or that are new (I added options to change the interface language, including when starting onboarding). Could you please translate them? 

![image](https://user-images.githubusercontent.com/81011038/161391051-51b7ed7e-1ca4-4f73-8c77-46fc5c7639b6.png)

**Comment by LAB02-Admin** [comment]
By the way, nothing relevant, but I noticed this word in your translations and I love it: `desenvolvedores`. Sounds so cool! Using that from now on 😆

**Comment by LeandroIssa** [comment]
> There are a few strings that I'd forgotten or that are new (I added options to change the interface language, including when starting onboarding). Could you please translate them?
> 
> ![image](https://user-images.githubusercontent.com/81011038/161391051-51b7ed7e-1ca4-4f73-8c77-46fc5c7639b6.png)

Done! All 100% again! Whatever you need, I'm always available to translate! 

![Captura de tela 2022-04-02 131231](https://user-images.githubusercontent.com/67451572/161391674-3cc6b0c5-c319-4b38-bcdc-fefe70b77858.png)

**Comment by LeandroIssa** [comment]
> By the way, nothing relevant, but I noticed this word in your translations and I love it: `desenvolvedores`. Sounds so cool! Using that from now on 😆

This word means developers, you can call yourself a "desenvolvedor"! =)

**Comment by LAB02-Admin** [comment]
The beta is ready:

https://github.com/LAB02-Research/HASS.Agent/releases/tag/b2022.4.2

There are a few things that aren't translated yet; the command/sensor type-names, since they're internally coupled, but I'll have that straightened out before the final release. I also just noticed when testing that not everything of the installer's translated, so we'll have to do that as well. But for now you can check if the interface's ok like this :) 

> Done! All 100% again! Whatever you need, I'm always available to translate!

Great, I'm glad, I'm updating HASS.Agent all the time 😁

**Comment by LeandroIssa** [comment]
> The beta is ready:
> 
> https://github.com/LAB02-Research/HASS.Agent/releases/tag/b2022.4.2
> 
> There are a few things that aren't translated yet; the command/sensor type-names, since they're internally coupled, but I'll have that straightened out before the final release. I also just noticed when testing that not everything of the installer's translated, so we'll have to do that as well. But for now you can check if the interface's ok like this :)
> 
> > Done! All 100% again! Whatever you need, I'm always available to translate!
> 
> Great, I'm glad, I'm updating HASS.Agent all the time 😁

I'm also very happy with the pre-release of the translation!

About the interface, it's OK, just one detail that needs to be fixed, the text in Configuration, Home Assistant API was behind the text box.

![Captura de tela 2022-04-02 183020](https://user-images.githubusercontent.com/67451572/161402036-f59f4a8e-1a99-484e-9b6e-ce3da788ee90.png)

About the translation, I fixed some details that I left out but I believe that when you put the command/sensor type-names for the release of the version to go along!

Please, when you have more things to translate let me know here and I'll run there to deliver it to you as soon as possible!

**Comment by LAB02-Admin** [comment]
>About the interface, it's OK, just one detail that needs to be fixed, the text in Configuration, Home Assistant API was behind the >text box.

Good catch! Fixed.

I made a different project for the missing strings of the installer:

https://poeditor.com/join/project/RMX0icxOSd

I'll let you know when I've updated HASS.Agent with the missing type names, that will probably be somewhere next week.

Thank you for the fun teamwork :)

**Comment by LeandroIssa** [comment]
> > About the interface, it's OK, just one detail that needs to be fixed, the text in Configuration, Home Assistant API was behind the >text box.
> 
> Good catch! Fixed.

Oh yes, thank you!

> I made a different project for the missing strings of the installer:
> 
> https://poeditor.com/join/project/RMX0icxOSd

Done!

![Captura de tela 2022-04-03 095230](https://user-images.githubusercontent.com/67451572/161429089-4f059984-d1c1-4572-8706-979a2545cff8.png)


> I'll let you know when I've updated HASS.Agent with the missing type names, that will probably be somewhere next week.
> 
> Thank you for the fun teamwork :)

Whatever you need, I'm always available! Thank you for your patience and attention! =)

**Comment by LAB02-Admin** [comment]
The installer apparantly has a hard limit on 260 characters 😕 

Could you please trim this line (it's only 8 characters too long):

> A configuração determinou que alguns dos pré-requisitos necessários para executar o [ProductName] estão ausentes. Este assistente o ajudará a obter e instalar esses pré-requisitos. Clique em "[Text_Next]" para continuar ou "[ButtonText_Cancel]" para sair do [Wizard].

**Comment by LAB02-Admin** [comment]
And could you please translate this one as well please (I'm changing the installer landing-page text to be a little bit friendlier):

> HASS.Agent is relased under the MIT license, which is a very short, simple and permissive license. You must agree to its <a href="">Licenses terms and conditions</a> before installing (don't worry, it's a really short read).

Thanks!

**Comment by LeandroIssa** [comment]
> The installer apparantly has a hard limit on 260 characters 😕
> 
> Could you please trim this line (it's only 8 characters too long):
> 
> > A configuração determinou que alguns dos pré-requisitos necessários para executar o [ProductName] estão ausentes. Este assistente o ajudará a obter e instalar esses pré-requisitos. Clique em "[Text_Next]" para continuar ou "[ButtonText_Cancel]" para sair do [Wizard].

Alguns dos pré-requisitos necessários para executar o [ProductName] estão ausentes. Este assistente o ajudará a obter e instalar esses pré-requisitos. Clique em "[Text_Next]" para continuar ou "[ButtonText_Cancel]" para sair do [Wizard].

Done! =)

> HASS.Agent is relased under the MIT license, which is a very short, simple and permissive license. You must agree to its Licenses terms and conditions before installing (don't worry, it's a really short read).

O HASS.Agent foi lançado sob a licença MIT, que é uma licença muito curta, simples e tolerante. Você deve concordar com os termos e condições das licenças antes de instalar (não se preocupe, é muito curta).

Done! =)
Whatever you need, just talk! <3

**Comment by LAB02-Admin** [comment]
I've re-released b2022.4.3 containing your translation tweaks, the fix for config panel and the installer translations:

https://github.com/LAB02-Research/HASS.Agent/releases/download/b2022.4.2/HASS.Agent.Installer.exe

You don't have to uninstall first, you can just run this one. Let me know if you find any flaws :)

**Comment by LeandroIssa** [comment]
> I've re-released b2022.4.2 containing your translation tweaks, the fix for config panel and the installer translations:
> 
> https://github.com/LAB02-Research/HASS.Agent/releases/download/b2022.4.2/HASS.Agent.Installer.exe
> 
> You don't have to uninstall first, you can just run this one. Let me know if you find any flaws :)

Perfect! I didn't find any flaws, everything 100%! I'm very happy! <3
Thank you very much for the care and attention given to the Brazilian Home Assistant community.

**Comment by LAB02-Admin** [comment]
Yay :) 

De nada!

**Comment by LAB02-Admin** [comment]
Hey @LeandroIssa, I've added all values for the lists (sensor names, entity types, etc) as well. It'll take me at least a week to get everything converted in the sourcecode to properly use the translations, so take your time!

If you ever need some context for an item, for instance an example of how/when it's used, let me know.

**Comment by LeandroIssa** [comment]
![Captura de tela 2022-04-06 112153](https://user-images.githubusercontent.com/67451572/161997057-89237a30-1d08-4eb2-a5d8-a9752e4887ad.png)

Hi!
Thanks for the feedback! I've translated everything!
I was able to understand from the context below in the text. Thank you for your effort and patience, I'm always available! <3

**Comment by LAB02-Admin** [comment]
Lightning fast as always, thanks :D

**Comment by LAB02-Admin** [comment]
Hi @LeandroIssa,

Hope you're ok over there on the other side of the ocean! Just checking up on something - I noticed that some types have the same name translated:

![image](https://user-images.githubusercontent.com/81011038/162154743-6ac82dc8-00c6-4868-b881-42345ada6d14.png)

![image](https://user-images.githubusercontent.com/81011038/162154755-76b6d726-66ef-456b-9c1f-b052ff1d98f4.png)

If that's how you use them in HA that's fine of course, just making sure :)

**Comment by LAB02-Admin** [comment]
Also added a few new ones - sorry this is going so messy! It's my first time implementing localization, so I'm learning on the go :)

![image](https://user-images.githubusercontent.com/81011038/162167333-bbeca47d-911f-4d3c-b262-b7fb0eee7d2e.png)

**Comment by LeandroIssa** [comment]
> Also added a few new ones - sorry this is going so messy! It's my first time implementing localization, so I'm learning on the go :)
> 
> ![image](https://user-images.githubusercontent.com/81011038/162167333-bbeca47d-911f-4d3c-b262-b7fb0eee7d2e.png)

Done too! You can count on what you need! =)

**Comment by LAB02-Admin** [comment]
> About these parts still in English, my fear was that they were intens that are in English in Home Assistant and I left it anyway, but now looking at Hass.Agent I realized they weren't so it's better to translate! So it's done!

The translations are only in the interface, code-wise everything stays the same 😄 

Thanks as always!

**Comment by LAB02-Admin** [comment]
Hi @LeandroIssa - there are a few new items to translate! This is the final list before the next release, there'll just be bugfixes from now on :)

**Comment by LAB02-Admin** [comment]
It's ready, let me know if anything's missing!

https://github.com/LAB02-Research/HASS.Agent/releases/download/b2022.11.0/HASS.Agent.Installer.exe

**Comment by LeandroIssa** [comment]
I'm passing by to let you know that I fixed some translations that were wrong. <3

**Comment by LAB02-Admin** [comment]
I've redeployed the beta with the latest translations if you're bored and want to have a look:

https://github.com/LAB02-Research/HASS.Agent/releases/download/b2022.11.1/HASS.Agent.Installer.exe

You can simply run the installer again :)

**Comment by LAB02-Admin** [comment]
Spoke a bit too soon 😬  Two more translations; one obscure one that I'd forgotten, and an extra info text when opening the satellite service config screen, explaining what exactly the service can be used for.

When these are done, I'm releasing the final version :)

**Comment by LeandroIssa** [comment]
All ready now! 100% translated! <3

**Comment by LAB02-Admin** [comment]
Thanks @LeandroIssa for translating again :) You're really setting the bar for the others :p

I've adopted a new release cycle; first I build the betas, without publishing the new to-be-translated strings (because that's a lot of work, and they change all the time). When the release candidate is ready, I publish them all at once and notify the translators. A few days later, I release the final version. Is that ok for you?

I just saw your translation also being added to the EdgeOS (Ubiquiti) integration. Really impressive and kind, everything you do for the Brazilian HA community!

**Comment by LeandroIssa** [comment]
I'm really excited about the news here for HASS.Agent, it's a program that really makes a difference! Thank you for your attention with the community!

> A few days later, I release the final version. Is that ok for you?

That's fine with me, whatever is best and simple for you!

> I just saw your translation also being added to the EdgeOS (Ubiquiti) integration. Really impressive and kind, everything you do for the Brazilian HA community!

Thanks for the recognition for the translations, more than 50 HACS components have already been translated, apart from the core and frontend of Home Assistant that I keep the translation at 100%. I believe that having the Home Assistant, the components and integration in our language makes a huge difference to the growth of the Brazilian community, having the recognition of a person outside of it makes me extremely happy! Thank you so!
