### ISSUE TITLE
Feature: output additional AudioSensors info

### ISSUE THREAD

**Issue by dimmuboy** [LAB02-Research/HASS.Agent#44]
When I add Audio sensor my output is always "High Definition Audio Device" but when I try to get my default audio device via powershell cmdlet https://github.com/frgnca/AudioDeviceCmdlets I get additional info f.e.
Name    : Headphones (High Definition Audio Device)

**Comment by LAB02-Admin** [comment]
Interesting! I'll have a look, thank you :)

**Comment by tachibanayui** [comment]
CoreAudio version 1.17.0 property `FriendlyName` return exactly what @dimmuboy wrote and the old `FriendlyName` property has been changed to `DeviceInterfaceFriendlyName`.

**Comment by LAB02-Admin** [comment]
Awesome, nice find @tachibanayui ❤️
