### ISSUE TITLE
feature request: location

### ISSUE THREAD

**Issue by Brtrnd** [LAB02-Research/HASS.Agent#50]
what would be the possibilities to add the location of the laptop?
https://docs.microsoft.com/en-us/windows/uwp/maps-and-location/get-location

**Comment by LAB02-Admin** [comment]
Hey @Brtrnd,

I actually just added that in the latest beta! 

https://github.com/LAB02-Research/HASS.Agent/releases/download/b2022.11.1/HASS.Agent.Installer.exe

You can just run it, no need to uninstall the current version.

It's the GeoLocation sensor :)
