### ISSUE TITLE
Bug: MQTT discovery doesn't work if device name has an apostrophe

### ISSUE THREAD

**Issue by mdrichardson** [LAB02-Research/HASS.Agent#53]
Might want to add a note about this or maybe do some validation for the device name, but I had set mine to `Michael's Desktop` and saw that the discovery message was published as: `homeassistant/binary_sensor/Michael's Desktop/michael_s_desktop_webcamactive/config`, but couldn't find the entities or devices being added to general HA or to the MQTT Integration. I changed my device name to `MichaelDesktop` and they were then added immediately. I believe spaces have worked in my MQTT names before, but I guess apostrophes don't.

**Comment by LAB02-Admin** [comment]
Fixed in latest beta: https://github.com/LAB02-Research/HASS.Agent/releases/tag/2022.12.0-beta4
