### ISSUE TITLE
Feature: use MQTT for integration communication

### ISSUE THREAD

**Issue by SamMousa** [LAB02-Research/HASS.Agent#58]
The agent uses MQTT to send sensor values to HASS.
It listens on a port to receive notifications.

The library for MQTT supports subscribing to events: https://github.com/dotnet/MQTTnet/blob/master/Samples/Client/Client_Subscribe_Samples.cs

You could (initially) implement this as something additional without removing the current implementation:
- Subscribe to a topic
- When receiving a message create a `Notification` instance for it
- Pass the instance to the notification manager

I don't really speak `.NET` or I would've implemented a PR myself.

The cool thing about using MQTT is that you could initially build it just in the agent for testing (and test it from HASS by using the MQTT service directly). The next step would be to have the HASS integration expose a notify service that internally uses MQTT for sending the notifications.

This should fully resolve issues with inbound connection blockers like firewalls and NAT.

It should be noted that this does require MQTT to be reachable somehow since that is not the case by default when exposing home assistant via Nabu Casa.

**Comment by LAB02-Admin** [comment]
Hey @SamMousa,

It currently already subscribes as well (to be able to receive commands). But having the integrations use MQTT internally is a nice idea though! Hadn't thought of that.

I'll keep it in my mind for future updates, could be a nice fallback if something can't be done through websockets (that's where I'm heading with notifications, but not everything can be done through them efficiently).

Thanks!

**Comment by SamMousa** [comment]
> Either that or invert the connection direction to have the agent open the connection to home assistant... rather than the other way around.

If the agent switches to websockets this will already be the case. And since it's bidirectional it would fully remove the need for a separate notification server.

**Comment by LAB02-Admin** [comment]
> What specific issues are you running into with websockets?

The new [mediaplayer integration](https://github.com/LAB02-Research/HASS.Agent-MediaPlayer); I didn't find a way to build that using websockets.

**Comment by ruifung** [comment]
> > What specific issues are you running into with websockets?
> 
> The new [mediaplayer integration](https://github.com/LAB02-Research/HASS.Agent-MediaPlayer); I didn't find a way to build that using websockets.

I just took a look at the media player integration, it seems like it's just sending simple text format payloads?

And looking at the HASS WebSocket API docs...

Couldn't you do something with the event bus, and a event subscribe_trigger? Then in the integration you could send a event with a device ID or something which the subscribe_trigger can use.

Well, either that or MQTT, I suppose.

**Comment by LAB02-Admin** [comment]
Hey @ruifung,

Interesting! From what I read, I figured you could only subscribe to existing entities, mostly because of the line:

> These are the same triggers syntax as used for [automation triggers](https://www.home-assistant.io/docs/automation/trigger/).

So hadn't looked into it much. But I'll go tinker with it for the next iteration of both integrations. Thanks for the tip.

**Comment by SamMousa** [comment]
You cannot register entities via websockets but maybe you don't need to. Just set them up during integration setup, then use websockets to update state!

**Comment by LAB02-Admin** [comment]
Figures, nice!

**Comment by ruifung** [comment]
@LAB02-Admin I mean, you don't need to, just (ab)use the event bus to post your own messages there. XD

hassagent_join_event
hassagent_heartbeat_event
hassagent_ping_request_event
etc.etc.etc..

Though, I suppose MQTT would be a lot "cleaner", especially since you can make use of the LWT message to detect when the client drops.

**Comment by SamMousa** [comment]
> However, all of this makes me think that 'just' using MQTT might be an easier solution instead of multiple technologies. thinking

MQTT Discovery doesn't support Media Players though. Note that you can use MQTT over websockets as well. Just use the mqtt service to publish messages...

For the sensors that makes sense, for the mediaplayer you could look into using something like: https://github.com/TroyFernandes/hass-mqtt-mediaplayer as inspiration or https://github.com/jonaseickhoff/hass-multiroom-mqtt-mediaplayer

Essentially one part that listens to MQTT messages and creates a media player, this can even be a separate integration not related to hass.agent.

And then hass agent just using MQTT over websockets to expose sensors etc

**Comment by LAB02-Admin** [comment]
I'm closing most feature requests from github's issue list. They're not ignored, just moved to the [HASS.Agent Issue Tracker](https://lab02research.youtrack.cloud/) (you can find your link in a comment above). 

That tracker allows me to organise better through what's pending, being done, being released, etc. - instead of one long list, which is beginning to stress me out :p

I will however post a reply here when I've implemented your request, and feel free to still post here when you have any questions/additions.
