### ISSUE TITLE
Feature: make right-click trayicon menu user-configurable

### ISSUE THREAD

**Issue by paccerdk** [LAB02-Research/HASS.Agent#59]
First of all, great piece of software, I can see you put a lot of work into it.

I used to use "[Home Assistant Desktop](https://community.home-assistant.io/t/home-assistant-desktop-macos-windows-and-linux-quick-and-easy-access-to-ha/196191)" which is now supposedly dead - I saw that you suggested your own software in this thread as an alternative, so I am trying to set it up as such.. 

I used Home Assistant Desktop for controlling my light brightness, in the way shown in the screenshot.
one click access to brightness. (without going through any submenus or anything)

I couldn't find any way to make a slider like that, did I miss something or is it just not a feature (yet?) in HASS agent?

Also, I would like to suggest more direct access to controls, ideally being able to click the tray icon once and then accessing the controls directly from there without having to open further submenus / more clicks.
The right click menu doesn't feel very necessary to me, since the main window, opened by double left click, gives me the same options

The following screenshot is basically what I am trying to achieve:
![homeass-desktop](https://user-images.githubusercontent.com/16404760/166117147-31f3e6a8-e4b5-4faa-9c98-93e0c50d97cc.png)

**Comment by LAB02-Admin** [comment]
Hi @paccerdk,

Sorry for the late reply - was away for a few days. From what I understand, Home Assistant Desktop was pretty much just a webbrowser-control, so it showed the HA dashboards. That's actually on the shortlist for the next version of HASS.Agent as well.

However, I completely agree with the trayicon menu being useless. I'll add the ability for users to decide for themselves what happens when they right-click, with the webbrowser-control being one of them. Thanks for the tip!

**Comment by paccerdk** [comment]
Thanks for your reply, looking forward for future updates!

For the record, I'd still love to see/like to request sliders. I wouldn't have to waste resources running the whole browser engine etc. Makes a lot more sense for audio, light and others instead of having incremental buttons and such - seems like a pretty essential thing to me.

**Comment by paccerdk** [comment]
You're right, that's exactly how home assistant desktop did it,  which in my opinion worked but wasn't ideal. 
I'd be completely fine with WebView and then native sliders "further down the road", ill take anything I can get.
What I am saying, is just that sliders was an actual suggestion (figured I'd better mention it, because of your renaming of this ticket and not commenting on native sliders in your initial response) - hopefully that makes sense ;)

the last URL i have for "home assistant desktop" download is  
`https://github.com/mrvnklm/homeassistant-desktop/releases/download/v1.4.10/Home-Assistant-Setup-1.4.10.exe`
which no longer works

The program did have an auto update feature, but I believe this was the latest version.

I've made the resulting file from the link **TEMPORARILY** available [here](https://home.paccer.dk/s/jzLjEYsL4ZfZ6Hg) (since its too big for uploading to this ticket)

**Comment by paccerdk** [comment]
Oh, and just as a side-note.
It seems the maintainer of homeassistant desktop just deleted the repository without any warning or notice. It may not even have been intentional? I remember reading somewhere, probably a ticket in the repository, that the project "wasn't dead" - this status may of course have changed the mean time.

its also my impression that nobody has been in contact with the maintainer since the deletion.

**Comment by LAB02-Admin** [comment]
> What I am saying, is just that sliders was an actual suggestion (figured I'd better mention it, because of your renaming of this ticket and not commenting on native sliders in your initial response) - hopefully that makes sense ;)

That does make sense, got it! I'll keep it in mind :) 

Thanks for sharing the installer, you can remove it now if you want

**Comment by LAB02-Admin** [comment]
This has been added in the latest beta:

https://github.com/LAB02-Research/HASS.Agent/releases/tag/2022.12.0-beta2

I'll keep the native implementation in mind, that would be best :) If something's missing/not working as you'd like/whatever in the beta, please reopen this ticket and let me know!

**Comment by paccerdk** [comment]
Wow, you've been busy ;) this is nothing less than amazing! you've made my day, new beta works great!

**Comment by LAB02-Admin** [comment]
Hey thanks for the uplifting feedback, you're very welcome! And thanks for testing :)
