### ISSUE TITLE
Bug: WebView doesn't work with desktop scaling

### ISSUE THREAD

**Issue by holdestmade** [LAB02-Research/HASS.Agent#62]
Great new feature but I have my desktop scaled to 125% and this causes the rendered webpage to be smaller than the configured window. If I set to 100% it works fine.

**Comment by LAB02-Admin** [comment]
I'll look into it, thanks, bloody scaling

**Comment by LAB02-Admin** [comment]
Release a hotfix that should fix this. Please note that other parts of HASS.Agent are now misaligned, sorry. Hopefully not too bad, let me know if something's unusable now.

https://github.com/LAB02-Research/HASS.Agent/releases/tag/2022.12.0-beta3

**Comment by holdestmade** [comment]
Thanks webview works fine now
