### ISSUE TITLE
Feature: labeling elements for those who are blind

### ISSUE THREAD

**Issue by blindndangerous** [LAB02-Research/HASS.Agent#65]
I found this from the official HA topic, and downloaded it.  I like it, from what I can tell, but everything is unlabeled.  I am a blind user and I use a screenreader called nvda to use the computer.  After installing this, it doesn't look like any of the buttons, lists, or tabs have proper labels.  They all just say button, list, or tab with a long string of numbers and metro at the end and nothing else.  Would it be possible to have labels added to what things are?  I'd be happy to help test if you can, just let me know.

**Comment by LAB02-Admin** [comment]
Hi @blindndangerous,

Thanks for reaching out! You are absolutely right, labeling is a mess. I'll try my best to label them, and yea then it'd be great if you could test and determine if the labels make sense. 

I'll reply here as soon as I have a test version ready!

**Comment by LAB02-Admin** [comment]
I've added initial support for screenreaders to the latest beta: 

https://github.com/LAB02-Research/HASS.Agent/releases/tag/2022.12.0-beta4

Could you please test it, and let me know if it's usable, and what can be improved? Thanks!

**Comment by LAB02-Admin** [comment]
The latest release includes this as well:

https://github.com/LAB02-Research/HASS.Agent/releases/tag/2022.12.0

I'm closing this ticket for now, but whenever you find time to test and want it improved, please reopen and let me know :)
