### ISSUE TITLE
Command "KeyCommand"

### ISSUE THREAD

**Issue by abel2660** [LAB02-Research/HASS.Agent#7]
What does the "KeyCode" parameter mean?

**Comment by LAB02-Admin** [comment]
You can choose [any of these keycodes](https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes) and they'll be simulated.

Currently limited to only one keycode per command, and using this list is a bit tedious. I'm working on a new version that supports multiple keys. You can also just press the keys when creating the command, and it'll look up the codes for you.

**Comment by abel2660** [comment]
Thanks

**Comment by abel2660** [comment]
Are there any way to simulate a "Ctrl" or a "Alt" key press?

**Comment by LAB02-Admin** [comment]
CTRL is `0x11` and ALT is `0x12`, but a combination like ALT + B can't be done with the current version.

If you want, you can try using something like [AutoHotkey](https://www.autohotkey.com) to do the key presses for you.
