### ISSUE TITLE
Bug: CpuLoad from Satellite Service doesn't work.

### ISSUE THREAD

**Issue by JvdMaat** [LAB02-Research/HASS.Agent#70]
On one of my two laptops, the CpuLoad for the Satellite Service doesn't work (returns 0).
When I add it through the local sensor, it gives a correct value.
Nothing in Satellite Logs showing any issues.

**Comment by LAB02-Admin** [comment]
This works fine on my end. Can you please provide some info:

- What Windows build do you have (possible a screenshot of the `winver.exe` output)
- What UI language
- Does the GPU load sensor work 
- What version of HASS.Agent

Thanks :)

**Comment by JvdMaat** [comment]
Apparently this was a fluke. After sleeping my laptop last night, and waking it up this morning, the satellite CPU sensor is now working fine.
Speaking of GPU, that lists Not Supported on my main system (With an integrated Intel 520)
![image](https://user-images.githubusercontent.com/90044149/170484356-b972bf21-bbe9-4e1d-875f-0d0e163ffeb1.png)
But works fine on the other which has AMD Radeon Graphics.

**Comment by LAB02-Admin** [comment]
Glad it's fixed. I use the librehardwareinfo library for that, so you could open a ticket there:

https://github.com/LibreHardwareMonitor/LibreHardwareMonitor

**Comment by JvdMaat** [comment]
I downloaded it, and it shows the GPU info:
![image](https://user-images.githubusercontent.com/90044149/170538777-fa89f644-ced6-46c1-bb57-51cca76abed2.png)

**Comment by LAB02-Admin** [comment]
I don't think intel gpus are supported through the library yet. You can however keep Librehardwareinfo running in the background, and use a wmi sensor to fetch the data.

There are some examples here:

https://hassagent.readthedocs.io/en/latest/wmi-examples/
