### ISSUE TITLE
Bug: Sleep command button does not do anything

### ISSUE THREAD

**Issue by JvdMaat** [LAB02-Research/HASS.Agent#72]
I created a Command for Sleep as a Button.
Pressing it in HA doesn't have any results. Checked the logs, and don't see any mention of it.
What does it do in the background, and in which user context (service or agent/user)

**Comment by JvdMaat** [comment]
This was apparently my fault. I had a desktop shortcut that I used which basically executes: (Since I always RDP into this machine, and doing a Start -> Power -> Sleep does NOT work over RDP. Despite the option being there)
`C:\Windows\System32\rundll32.exe powrprof.dll,SetSuspendState 0,1,0`
And that no longer worked either.
I then remembered I saw in the docs that hybernate had to be off, so I had executed a `powercfg /h off` earlier today. Which apparently broke remote sleep ability.
After running `powercfg /h on`, both my sleep shortcut and the HA button work normally.

**Comment by LAB02-Admin** [comment]
Interesting, thanks for letting me know!

**Comment by heisenberg2980** [comment]
@JvdMaat after executing "powercfg /h on" the sleep command button actually hibernates the computer instead of putting it to sleep, did you find out why the sleep command does not work when hibernate is off?

**Comment by JvdMaat** [comment]
I did not. This is some Microsoft thing. I'm not in the desktop side of things as much anymore to know what is going on.
