### ISSUE TITLE
HASS.Agent crashing

### ISSUE THREAD

**Issue by klkohl** [LAB02-Research/HASS.Agent#77]
Just intalled it on on Windows 10 machine. Every time I try to start it, it crashes. I uninstalled and reinstalled and it still crashes.

**Comment by LAB02-Admin** [comment]
You're not giving me much to work with here 😁 

Do you get a message or popup when it crashes? And could you please send the content of the logs (if there are any), you can find them at `%appdata%\LAB02 Research\HASS.Agent\logs`.

**Comment by klkohl** [comment]
Sorry about that. It's working now. I didn't see any message or popup. For what it's worth I'm attaching the log from yesterday.

[2022-06-08_HASS.Agent.Satellite.Service_20220608.log](https://github.com/LAB02-Research/HASS.Agent/files/8873600/2022-06-08_HASS.Agent.Satellite.Service_20220608.log)

**Comment by LAB02-Admin** [comment]
Interesting log, thanks for sharing - I'll better handle unauthorized connections. Glad it's fixed :)
