### ISSUE TITLE
Bug: Satellite Service fails under Windows 7

### ISSUE THREAD

**Issue by Otanar1** [LAB02-Research/HASS.Agent#79]
**Describe the bug**
I can't activate the Satellite Service, I already reinstalled the service, Hass.Agent, .NET 3.1.25, 5.0.17, 6.0.5, 7.0.0-preview.4 and nothing worked.
I've run it as administrator and the problem persists.
----

**Screenshots**

**Misc info (please complete the following information):**
 - Windows build (ideally screenshot/info of `winver.exe` output): Windows 7 Profissional - Version 6.1 (Compilation 7601: Service Pack 1) 
 
 ![image](https://user-images.githubusercontent.com/87052646/172885051-ef8860e3-570d-432f-a9f1-3b961ca23006.png)

 - Windows' UI language: PT-BR (Português - Brasil)
 
 - HASS.Agent version: 2022.11.4 

![image](https://user-images.githubusercontent.com/87052646/172885161-668e6e8f-01b5-455b-aa79-ede0237d1506.png)

.NET: 

![image](https://user-images.githubusercontent.com/87052646/172886192-43740cde-b785-4586-b8c3-5e0adcb7be1b.png)

Please check what's applicable (multiple answers possible):

 - [x] Installed via installer
 - [ ] Installed manually
 - [ ] Problem occurs in HASS.Agent
 - [x] Problem occurs in Satellite Service

**Logs**
![image](https://user-images.githubusercontent.com/87052646/172886355-99db8e18-1322-4faa-b09b-df93f84c7b21.png)
![image](https://user-images.githubusercontent.com/87052646/172886414-285aeaa7-834e-4deb-ab4a-626675e111c5.png)
[[2022-06-09] HASS.Agent_service_enabled_20220609.log](https://github.com/LAB02-Research/HASS.Agent/files/8871791/2022-06-09.HASS.Agent_service_enabled_20220609.log)
[[2022-06-09] HASS.Agent_service_reinstall_20220609.log](https://github.com/LAB02-Research/HASS.Agent/files/8871792/2022-06-09.HASS.Agent_service_reinstall_20220609.log)
[[2022-06-09] HASS.Agent_20220609.log](https://github.com/LAB02-Research/HASS.Agent/files/8871793/2022-06-09.HASS.Agent_20220609.log)
[[2022-06-08] HASS.Agent_20220608.log](https://github.com/LAB02-Research/HASS.Agent/files/8871795/2022-06-08.HASS.Agent_20220608.log)

**Comment by LAB02-Admin** [comment]
Hi @Otanar1,

Thanks for the detailed reports :) 

I haven't actually tested hass.agent or the satellite service under windows 7. Give me some time to setup a Win7 environment so I can see if I can get it to work!

**Comment by LAB02-Admin** [comment]
Hi @Otanar1,

So I've been playing with it, but I can't even get HASS.Agent to work *at all* on Windows 7 heh. So it's odd that you can, but that's fine. 

I did however find a way for you to run the Satellite Service, if you want. Open an elevated command prompt, and type these commands:

`sc.exe create "HASS.Agent Satellite Service" binPath= "C:\Program Files (x86)\LAB02 Research\HASS.Agent Satellite Service\HASS.Agent.Satellite.Service.exe"`

`sc.exe failure "HASS.Agent Satellite Service" reset= 86400 actions= restart/60000/restart/60000//1000`

`sc.exe config "HASS.Agent Satellite Service" start= auto`

`sc.exe start "HASS.Agent Satellite Service"`

The service should now be installed and started. I'll also fix it for the next release.

**Comment by Otanar1** [comment]
> Hi @Otanar1,
> 
> So I've been playing with it, but I can't even get HASS.Agent to work _at all_ on Windows 7 heh. So it's odd that you can, but that's fine.
> 
> I did however find a way for you to run the Satellite Service, if you want. Open an elevated command prompt, and copy/paste these commands:
> 
> `sc.exe create "HASS.Agent Satellite Service" binPath= "C:\Program Files (x86)\LAB02 Research\HASS.Agent Satellite Service\HASS.Agent.Satellite.Service.exe"`
> 
> `sc.exe failure "HASS.Agent Satellite Service" reset= 86400 actions= restart/60000/restart/60000//1000`
> 
> `sc.exe config "HASS.Agent Satellite Service" start= auto`
> 
> `sc.exe start "HASS.Agent Satellite Service"`
> 
> The service should now be installed and started. I'll also fix it for the next release.

Thanks for the feedback @LAB02-Admin .

Version 2022.11.4 works on Windows 7, 2022.12.0 does not.
What you gave me worked, now the service is working.
![Satellite Service](https://user-images.githubusercontent.com/87052646/174121998-b24deac2-7911-4e1e-936f-dac2a70df7f9.jpg)

Thanks for the excellent work.
Now I just need to solve the problem with the version 2022.12.0, for now I will not update.

**Comment by LAB02-Admin** [comment]
Hey @Otanar1,

I've been trying a few options, but the requirement of the latest Windows SDK prevents HASS.Agent from starting. I've installed the SDK on W7 (as a 'why not' attempt), but didn't help.

So I'm sorry, but it looks like 2022.11.4 is the last version that's supported on Windows 7 :(

Closing this now, if you ever come across a potential solution let me know and I'll test it.

For the record, this is the error Visual Studio gave:

```
Exception thrown: 'System.TypeInitializationException' in Microsoft.Windows.SDK.NET.dll
```

**Comment by Otanar1** [comment]
Hello @LAB02-Admin 

I see, I knew that one day I would have to migrate to a newer windows, is that 7 still works so well 😢
Next week I'll test a few more things, any news I'll let you know.
The notifications don't work here either, I'll install Hass.agent on the other PC I have here with windows 10 and test if the problem is with windows 7 or something else on my network.
Thank you for the feedback and congratulations for the excellent work and dedication.

**Comment by jocke92** [comment]
I don't manage to get it working in Windows 7 either. I did download the latest version. Not able to upgrade that computer to 10 sadly. But I do understand that there's no Windows 7 support

**Comment by LAB02-Admin** [comment]
Hey @Otanar1 and @jocke92, thanks to the fix suggested in ticket #113, I have HASS.Agent working under Windows 7 (the mediaplayer functionality will be disabled though). 

It'll be in the next beta

**Comment by Otanar1** [comment]
Hello @LAB02-Admin 

Amazing, I wasn't already happy with the current functioning, expanding it will be phenomenal.
I'm looking forward to the fix.
Thank you for the dedication and congratulations for the excellent work and dedication.

**Comment by LAB02-Admin** [comment]
You can try the latest beta: https://github.com/LAB02-Research/HASS.Agent/releases/tag/2022.13.0-beta2

**Comment by Otanar1** [comment]
> You can try the latest beta: https://github.com/LAB02-Research/HASS.Agent/releases/tag/2022.13.0-beta2

Hello @LAB02-Admin
I've installed it and it's in testing.
I still don't get notifications, even with everything set up.
I noticed that the web view is not dynamic so it doesn't adjust things to the window size.
I noticed that it is asking for login every time I restart HASS AGENT, which is a nuisance, especially for those who have 2-factor security.
Thank you for your dedication.

**Comment by LAB02-Admin** [comment]
>  I still don't get notifications, even with everything set up.

Looks like notifications won't work as-is, because HASS.Agent uses Windows' notifications system. I am planning to implement my own system, because there are a lot of limitations in the Windows one, so when that's done it should work on W7 as well.

>  I noticed that the web view is not dynamic so it doesn't adjust things to the window size.

You mean resize the content of the webpage to the size of the window? Interesting, I'll see if that can be done and if so, make it a setting.

>  I noticed that it is asking for login every time I restart HASS AGENT, which is a nuisance, especially for those who have 2-factor security.

With a webview? That shouldn't happen, it has cookies enabled and is basically like a regular browser. Is the `clear cache every x days` setting still on 0 days? It's available under config -> local storage -> bottom webview section.

**Comment by Otanar1** [comment]
> > I still don't get notifications, even with everything set up.
> 
> Looks like notifications won't work as-is on W7, because HASS.Agent uses Windows' notifications system. I am planning to implement my own system, because there are a lot of limitations in the Windows one, so when that's done it should work on W7 as well.

Great news, I will eagerly await this update

> > I noticed that the web view is not dynamic so it doesn't adjust things to the window size.
> 
> You mean resize the content of the webpage to the size of the window? Interesting, I'll see if that can be done and if so, make it a setting.

That, automatic resizing.
The HASS Workstation Service has this.
https://github.com/sleevezipper/hass-workstation-service

> > I noticed that it is asking for login every time I restart HASS AGENT, which is a nuisance, especially for those who have 2-factor security.
> 
> With a webview? That shouldn't happen, it has cookies enabled and is basically like a regular browser. Is the `clear cache every x days` setting still on 0 days? It's available under config -> local storage -> bottom webview section.

I found it strange too. The webview cache clearing is at 0 days. But every time I restart HASS.Agent it is asking to login again
![image](https://user-images.githubusercontent.com/87052646/184649871-68fc29da-19e3-4c65-b731-aea342695d07.png)
