### ISSUE TITLE
Bug: MQTT disconnects before sleep, grace period unreliable

### ISSUE THREAD

**Issue by lbandi2** [LAB02-Research/HASS.Agent#85]
The program works perfectly, but whenever I resume my computer from sleep, Hass agent reports 'MQTT failed to connect' which is kind of annoying to dismiss the notification event though it reconnects just fine (after resuming).

**To Reproduce**
1. Let your windows session go to sleep
2. Resume
3. Message should pop up

**Expected behavior**
Hass agent should detect when the computer goes to sleep so as to not notify that it can't connect to MQTT.

 - Windows 11
 - HASS.Agent version: 2022.12.0-beta4

**Comment by LAB02-Admin** [comment]
Have you tried setting this to a higher value:

![image](https://user-images.githubusercontent.com/81011038/173901666-6a3047dd-e677-4a90-a4ab-f55b7576f265.png)

**Comment by lbandi2** [comment]
So after testing it yesterday, I set the option you highlited to ~16-17 minutes and the sleep time of my pc to 15 minutes. What I found today is that the message occurs anyway and I had the feeling that it was before going to sleep, but it happens the instant that the pc resumes.

Any ideas?

**Comment by LAB02-Admin** [comment]
Interesting, thanks for checking that out! Hadn't occured to me that the disconnect can happen before going to sleep, that can mess with the counter. 

I'll improve it and let you know

**Comment by lbandi2** [comment]
Awesome, let me know if you need logs or anything else.

**Comment by LAB02-Admin** [comment]
I've merged all tickets related to this issue into a central pinned one: [#204]

Closing this one to keep it in one place.
