### ISSUE TITLE
Full-screen mode sensor

### ISSUE THREAD

**Issue by DivanX10** [LAB02-Research/HASS.Agent#88]
I didn't find it in the [documentation hass agent](https://hassagent.readthedocs.io/en/latest) how to get a sensor that shows which mode the application is in, fullscreen or not. For a visual example, I post data from the IOTLink sensor taken from MQTT Explorer. You can see FullScreen False\True here, and all the values are also useful, since they can be used for various tasks. For example, so that you can automate the highlighting for different content. If we watch movies in the browser not in full-screen mode, then we do not turn on ambient, and if we watch in full-screen mode, then we turn on ambient. For understanding, watch [video Home Assistant. Automating Hyperion](https://youtu.be/IZEbdxyDzDo) and below I posted working sensors for IOTLink, I would like to see something like this in HASS Agent

```
If the browser is running

{
  "Id": "15836",
  "SessionId": "1",
  "ProcessName": "browser",
  "StartDateTime": "2022-06-16 18:08:03",
  "Uptime": "00:03:40:37",
  "Uptime": "00:03:40:45",
  "MemoryUsed": "1250",
  "ProcessorUsage": "0",
  "MainWindowTitle": "New Issue · LAB02-Research/HASS.Agent – Яндекс.Браузер",
  "FullScreen": "False",
  "Status": "Running",
  "Windows": [
    "New Issue · LAB02-Research/HASS.Agent – Яндекс.Браузер",
    "Chrome Legacy Window"
  ],
  "ClassNames": [
    "YandexBrowser_WidgetWin_1",
    "Chrome_RenderWidgetHostHWND"
  ]
}


If the game is running
{
  "Id": "1580",
  "SessionId": "1",
  "ProcessName": "haloinfinite",
  "StartDateTime": "2022-06-16 22:10:15",
  "Uptime": "00:00:00:03",
  "MemoryUsed": "0",
  "ProcessorUsage": "0",
  "MainWindowTitle": "Halo Infinite",
  "FullScreen": "True",
  "Status": "Running",
  "Windows": [
    "Halo Infinite"
  ],
  "ClassNames": [
    "Halo Infinite"
  ]
}

```

Template sensors are used to determine the fullscreen mode for each application

```
#Video player. Pulling out the status of the fullscreen mode
  - platform: mqtt
    name: "IOT Link. PC Livingroom. VideoPlayers. FullScreen"
    unique_id: sensor iot link pc livingroom videoplayers fullscreen
    object_id: iot link pc livingroom videoplayers fullscreen
    state_topic: "iotlink/workgroup/livingroom/process-monitor/processes/videoplayers/sensor"
    value_template: "{{ value_json.FullScreen }}"
    qos: 0
    icon: mdi:desktop-mac

#Games. Pulling out the status of the fullscreen mode
  - platform: mqtt
    name: "IOT Link. PC Livingroom. Games. FullScreen"
    unique_id: sensor iot link pc livingroom games fullscreen
    object_id: iot link pc livingroom games fullscreen
    state_topic: "iotlink/workgroup/livingroom/process-monitor/processes/games/sensor"
    value_template: "{{ value_json.FullScreen }}"
    qos: 0
    icon: mdi:desktop-mac
```

Then I created sensors from two sensors that check each other and if the application is actually running and it is in full-screen mode, it will be True, if the application is minimized, it will be False
```
#Full-screen mode sensor for games
  - platform: template
    sensors:
      iotlink_pc_livingroom_game_fullscreen_mode:
        friendly_name: "Game. Full-screen mode"
        icon_template: mdi:google-controller
        value_template: >
            {% set game = states("binary_sensor.livingroom_games") %}
            {% set game_fullscreen = states("sensor.iot_link_pc_livingroom_games_fullscreen") %}
            {% if game == 'on' and game_fullscreen == 'True' %} on
            {% else %} off
            {% endif %}


#Full-screen mode sensor for video player
  - platform: template
    sensors:
      iotlink_pc_livingroom_videoplayers_fullscreen_mode:
        friendly_name: "Video player. Full-screen mode"
        icon_template: mdi:theater
        value_template: >
            {% set videoplayers = states("binary_sensor.livingroom_videoplayers") %}
            {% set videoplayers_fullscreen = states("sensor.iot_link_pc_livingroom_videoplayers_fullscreen")%}
            {% if videoplayers == 'on' and videoplayers_fullscreen == 'True' %} on
            {% else %} off
            {% endif %}

#Fullscreen mode sensor for YouTube
  - platform: template
    sensors:
      iotlink_pc_livingroom_youtube_fullscreen_mode:
        friendly_name: "YouTube. Full-screen mode"
        icon_template: mdi:youtube
        value_template: >
            {% set youtube = states("sensor.iotlink_pc_livingroom_browser_channel") %}
            {% set browsers_fullscreen = states("sensor.iot_link_pc_livingroom_browsers_fullscreen") %}
            {% if youtube == 'YouTube' and browsers_fullscreen == 'True' %} on
            {% else %} off
            {% endif %}
```

**Comment by LAB02-Admin** [comment]
Hi @DivanX10,

Thank you for all the info! You've really built an impressive setup ❤️ 

This request is on the todo list, it'll be implemented in the next version: [[hassagent-92](https://lab02research.youtrack.cloud/issue/hassagent-92)]

To see what I'm working on and what's planned, you can check the issue tracker: [https://lab02research.youtrack.cloud/](https://lab02research.youtrack.cloud/)

On the left there's a `Planned For Next Release` list, however that's not definitive. If something important (or really cool) comes up, it can always be added.

So keep letting me know what you want :) 

(I'm closing this because I only keep bug tickets open in github, all others go to the issue tracker - I'll still let you know here when I've implemented this!)

**Comment by qguv** [comment]
Hey @LAB02-Admin, it looks like this feature can only tell when specific windows, with a known name, are in full-screen mode (and even this feature seems to have some limitations, see #184). At home I'd like to dim the lights when people are playing any content in fullscreen, regardless of which window it is. Something like the active window sensor, but as a binary sensor reporting whether the active window (whatever it is) is in full-screen. Would it be possible to add a sensor for that?
