### ISSUE TITLE
[Enhancement] Default MQTT broker URL to the home assistant URL

### ISSUE THREAD

**Issue by SecretiveShell** [LAB02-Research/HASS.Agent#9]
A large majority of home assistant users run Hass OS and the mosquito addon, or otherwise run their MQTT broker from the same machine as their home assistant  instance. Because of this it makes sense to use the Home assistant URL provided in step 5 of the onboarding process as the default MQTT broker plugin in step 6.

**Comment by LAB02-Admin** [comment]
Good thinking @SecretiveShell :) Will do, thanks!

**Comment by LAB02-Admin** [comment]
Added in v2022.1.4
