### ISSUE TITLE
Tray Icon not opening on other virtual Desktops

### ISSUE THREAD

**Issue by currydani** [LAB02-Research/HASS.Agent#91]
I am using the Winows virtual Desktops (on the bottom if you press win+tab), and i noticed that you can only use the right click on the tray icon to show the webview on one single virtual Desktop. If you switch to a different one than the one you started the Agent, it won't display anything. Is this a bug or just something that can't be changed?

**Comment by LAB02-Admin** [comment]
I don't use virtual desktops, but I think that's because the webview form is already tied to one desktop.

You could try disabling `keep page loaded in the background`, so it loads a new one every time you right-click.

**Comment by currydani** [comment]
That actually did the trick, thank you!
