### ISSUE TITLE
Feature: make logs to satellite service easier to get to when there's an issue

### ISSUE THREAD

**Issue by sdwilsh** [LAB02-Research/HASS.Agent#96]
**Is your feature request related to a problem? Please describe.**
It took me a while to locate the satellite service logs to actually file an issue (#95). 

**Describe the solution you'd like**
I'd love for this dialog to have a link to the logs instead of saying to look at them with no indication of where they might be.
![image](https://user-images.githubusercontent.com/656602/175792412-01544c2b-ae82-42d6-a77f-de1c03ee3d9e.png)

**Describe alternatives you've considered**
Better documentation might be okay too!

**Additional context**
 In the [documentation](https://hassagent.readthedocs.io/en/latest/configuration/#9-satellite-service), I found this:
> If the satellite service doesn't work as expected, please use the `open service logs folder` to locate its logs, and attach the latest one when sending a bug report.

What I eventually realized is that it wants me to click the "open service logs folder" button in the "Satellite Service" section, but that wasn't very obvious.

**Comment by LAB02-Admin** [comment]
It's mentioned here in the screen you posted:

![image](https://user-images.githubusercontent.com/81011038/175805848-7d33ead7-a34c-455b-b2fd-cc6dcea7d008.png)

But I guess I could just add the button there too, will do.

[[hassagent-110](https://lab02research.youtrack.cloud/issue/hassagent-110)]

I'm closing this ticket to keep all pending tickets centralised and the github list clean, but I'll post here when you request has been implemented :)
