### ISSUE TITLE
Feature: sensor for audio playback device

### ISSUE THREAD

**Issue by sdwilsh** [LAB02-Research/HASS.Agent#97]
**Is your feature request related to a problem? Please describe.**
My end goal is something like [SoundSwitch](https://github.com/Belphemur/SoundSwitch), but instead of my manually having to change my audio devices, I want Home Assistant, via HASS.Agent, to do that for me.  In some contexts, I might want to use my wireless headset for audio playback and recording, but other times I might want to use my dedicated microphone for recording and play audio out of my speakers.

**Describe the solution you'd like**
At a minimum, having a sensor for the current audio playback device would be useful.  Adding commands to update the audio playback and recording devices would be nice to have.

**Describe alternatives you've considered**
Haven't thought of any as of yet.

**Comment by LAB02-Admin** [comment]
Hi @sdwilsh,

There's already a sensor to detect the current audio playback device; the `audio` multivalue-sensor. This is its description:

```
Provides information various aspects of your device's audio:

Current peak volume level (can be used as a simple 'is something playing' value).

Default audiodevice: name, state and volume.

Summary of your audio sessions: application name, muted state, volume and current peak volume.
```

For instance, it'll create a sensor `sensor.your_device_audio_default_device` with the name of the default audio device. You'll also get `sensor.your_device_audio_default_device_state` with its state, and `sensor.your_device_audio_audio_sessions` with all current audio sessions. 

I didn't think it was possible to programmatically change Windows' default audio device through code, but looks like SoundSwitch does just that. So I'll look into it and see if I can port it. 

Created a ticket: [[hassagent-109](https://lab02research.youtrack.cloud/issue/hassagent-109)]

I'm closing this ticket to keep all pending tickets centralised and the github list clean, but I'll post here when you request has been implemented :)

Let me know if you need further help with the sensor.

**Comment by tachibanayui** [comment]
I have the exact requirement. After some research, I found [nircmd](https://www.nirsoft.net/utils/nircmd.html), a command line tool for changing various Windows settings without UI.

Create a custom command: `nircmd setdefaultsounddevice <your device>`  and expose it as a button.
[Nircmd documentation](http://www.nirsoft.net/utils/nircmd2.html#using)

You can also use `input_select` helper + automation to create a dropdown in lovelace like so:
![image](https://user-images.githubusercontent.com/33594017/197379880-1c853650-d2f9-4dc9-969a-f207df55575f.png)

One problem I haven't figured out is updating the `input_select`s if I change my audio device in windows. The audio sensor always returns "Realtek (R) Audio" when I use my front io or line-in audio jack.  I am still waiting for #44 to be implemented or find another workaround

I hope this helps you

**Comment by LAB02-Admin** [comment]
@tachibanayui, thanks for that, I'll add it to the docs :)

#44 was implemented in the latest version, let me know if it's still not good enough

**Comment by tachibanayui** [comment]
Yeah, I think it is good enough, I built my own `HassAgent.Shared.dll` before the update to test this, and it works flawlessly. 
Thanks for letting me know
