### ISSUE TITLE
Bug: Fix/improve DPI handling

### ISSUE THREAD

**Issue by gorbunovav** [LAB02-Research/HASS.Agent#99]
**Describe the bug**
Despite `HASS.Agent` app reporting that it is `Per-monitor DPI Aware` the DPI processing is not correct.
It seems that only the main window looks ok, all other windows have elements sizing issues.

Current workaround is to override DPI settings for the `HASS.Agent` executable with the "System (Enhanced)" value (which disables DPI handling by the application).

Possible solutions: improve interface scaling or make the app report itself as non-DPI Aware to let the OS handle scaling.

**To Reproduce**
1. Set display scale to something greater than 100%
2. Restart `HASS.Agent` app
3. Open tray menu, configuration window, quick actions window
4. See issues with elements sizing

**Expected behavior**
Interfaces scales correctly

**Screenshots**
<img src="https://user-images.githubusercontent.com/2665015/176049636-b8f25469-6076-4e7b-a109-3f4045234915.png" width="200"><img 
src="https://user-images.githubusercontent.com/2665015/176049719-dca7e3ab-4e7a-43b1-9b73-359e5a1bb326.png" width="200"><img 
src="https://user-images.githubusercontent.com/2665015/176049673-6bd6ca15-f0ea-4f4a-8afe-ea451458aa82.png" width="200">

**Misc info (please complete the following information):**
 - Windows build (ideally screenshot/info of `winver.exe` output):  Windows 11 Pro 22H2 22621.160
 - Windows' UI language: English
 - HASS.Agent version: 2022.13.0-beta1

Please check what's applicable (multiple answers possible):

 - [x] Installed via installer
 - [ ] Installed manually
 - [x] Problem occurs in HASS.Agent
 - [ ] Problem occurs in Satellite Service

**Comment by LAB02-Admin** [comment]
I've created a ticket: [[hassagent-112](https://lab02research.youtrack.cloud/issue/hassagent-112)]

I'm closing this ticket, not because I'm not doing it, but to keep the GitHub list tidy and all my todo's in one place. I'll report back here when I've fixed this!

**Comment by gorbunovav** [comment]
@LAB02-Admin what about disabling the `DpiAwareness` flag for the app for now?
https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/winforms/

https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/winforms/windows-forms-add-configuration-element (check the `DpiAwareness` key).

Windows is able to handle the app resizing ok, as far as I can see:
<img width="671" alt="Screenshot 2022-06-28 132334" src="https://user-images.githubusercontent.com/2665015/176156600-1b144886-aa15-43e7-a02c-599ee371b093.png">

**Comment by LAB02-Admin** [comment]
Yea that was my initial workaround, but then the new webview doesn't render correctly [#62] :(

**Comment by gorbunovav** [comment]
>Current workaround is to override DPI settings for the HASS.Agent executable with the "System (Enhanced)" value (which disables DPI handling by the application).

@LAB02-Admin with this workaround the webview sizing is correct for me 🤔So not sure what was causing issues in #62

**Comment by LAB02-Admin** [comment]
Oh, interesting! I'll look into it and do some more tests, thanks :)

**Comment by ezpl** [comment]
> @LAB02-Admin what about disabling the `DpiAwareness` flag for the app for now? https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/winforms/
> 
> https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/winforms/windows-forms-add-configuration-element (check the `DpiAwareness` key).
> 
> Windows is able to handle the app resizing ok, as far as I can see: <img alt="Screenshot 2022-06-28 132334" width="671" src="https://user-images.githubusercontent.com/2665015/176156600-1b144886-aa15-43e7-a02c-599ee371b093.png">

Wanted to test this by adding an app-config file in the HASS.Agent directory. Unfortunately it does not seem to work. Might need to be defined in the application itself to be read?

_Hass.Agent.exe.config_
```xml
<configuration>
  <System.Windows.Forms.ApplicationConfigurationSection>
    <add key="DpiAwareness" value="false" />
  </System.Windows.Forms.ApplicationConfigurationSection>
</configuration>
```

**Comment by LAB02-Admin** [comment]
Implemented in the latest beta, let me know how it works out: https://github.com/LAB02-Research/HASS.Agent/releases/tag/2022.13.0-beta2

**Comment by gorbunovav** [comment]
@LAB02-Admin Hi! Yes, it works for me. Thank you!
